using MacroDeck.Plugin.Cli.Building;
using MacroDeck.Plugin.Cli.Scaffolding;

namespace MacroDeck.Plugin.Cli.Tests.UnitTests;

/// <summary>
/// The <c>macrodeck-build.json</c> contract. <c>new</c> has written this file since #641 and the packaging
/// guide documents its shape, so it is a published developer-facing format: the first fixture below pins
/// that what <c>new</c> emits today still reads back, and the rest pin that a recipe which could only
/// misbuild is refused before any tool is launched.
/// </summary>
[TestFixture]
public class PluginBuildConfigReaderTests
{
	private static readonly string[] _emptyArgumentVector = ["-p", ""];

	private string _project = null!;

	[SetUp]
	public void SetUp() => _project = Directory.CreateTempSubdirectory("macrodeck-build-config-tests-").FullName;

	[TearDown]
	public void TearDown() => Directory.Delete(_project, recursive: true);

	[Test]
	public void A_configuration_new_writes_today_reads_back_with_every_target_intact()
	{
		// Generated by the writer 'new' actually uses, not hand-copied, so this fails if either side drifts.
		var request = new PluginScaffoldRequest
		{
			Id = "com.example.fixture",
			Name = "Fixture",
			Publisher = "Example",
			Description = "A fixture.",
			License = "MIT",
			ProjectName = "Fixture",
			Output = _project,
			Platforms = PluginScaffoldDefaults.KnownPlatforms
		};

		var result = Read(PluginBuildConfig.Build(request));

		Assert.Multiple(() =>
		{
			Assert.That(result.FailureReason, Is.Null, result.FailureMessage);
			Assert.That(result.Targets!.Keys, Is.EquivalentTo(PluginScaffoldDefaults.KnownPlatforms));

			foreach (var rid in PluginScaffoldDefaults.KnownPlatforms)
			{
				Assert.That(result.Targets[rid].Executable, Is.EqualTo("dotnet"));
				Assert.That(result.Targets[rid].Arguments, Does.Contain(rid));
				Assert.That(result.Targets[rid].Output, Is.EqualTo($"bin/publish/{rid}"));
			}
		});
	}

	[Test]
	public void A_version_this_tool_does_not_understand_is_refused_rather_than_guessed_at()
	{
		var result = Read("""{ "version": 2, "targets": { "win-x64": { "executable": "x", "output": "out" } } }""");

		Assert.Multiple(() =>
		{
			Assert.That(result.FailureReason, Is.EqualTo(PluginBuildFailureReason.BuildConfigInvalid));
			Assert.That(result.FailureMessage, Does.Contain("2").And.Contain("1"));
		});
	}

	[Test]
	public void A_structurally_unusable_target_is_refused_and_the_message_names_the_runtime_identifier()
	{
		var missingExecutable = Read("""{ "version": 1, "targets": { "win-x64": { "output": "out" } } }""");
		var missingOutput = Read("""{ "version": 1, "targets": { "linux-x64": { "executable": "make" } } }""");
		var nonStringArgument =
			Read(
				"""{ "version": 1, "targets": { "osx-arm64": { "executable": "make", "arguments": ["ok", 7], "output": "out" } } }""");
		var noTargets = Read("""{ "version": 1, "targets": {} }""");

		Assert.Multiple(() =>
		{
			Assert.That(missingExecutable.FailureReason, Is.EqualTo(PluginBuildFailureReason.BuildConfigInvalid));
			Assert.That(missingExecutable.FailureMessage, Does.Contain("win-x64").And.Contain("executable"));

			Assert.That(missingOutput.FailureReason, Is.EqualTo(PluginBuildFailureReason.BuildConfigInvalid));
			Assert.That(missingOutput.FailureMessage, Does.Contain("linux-x64").And.Contain("output"));

			Assert.That(nonStringArgument.FailureReason, Is.EqualTo(PluginBuildFailureReason.BuildConfigInvalid));
			Assert.That(nonStringArgument.FailureMessage, Does.Contain("osx-arm64").And.Contain("1"));

			Assert.That(noTargets.FailureReason, Is.EqualTo(PluginBuildFailureReason.BuildConfigInvalid));
		});
	}

	[Test]
	public void An_empty_argument_is_accepted_because_a_recipe_is_not_only_ever_dotnet()
	{
		// '-p:Something=' is a legitimate vector element, and the format is deliberately not .NET-specific.
		var result =
			Read(
				"""{ "version": 1, "targets": { "win-x64": { "executable": "make", "arguments": ["-p", ""], "output": "out" } } }""");

		Assert.That(result.FailureReason, Is.Null, result.FailureMessage);
		Assert.That(result.Targets!["win-x64"].Arguments, Is.EqualTo(_emptyArgumentVector));
	}

	[Test]
	public void A_path_that_leaves_the_project_directory_is_refused()
	{
		var escaping =
			Read("""{ "version": 1, "targets": { "win-x64": { "executable": "make", "output": "../elsewhere" } } }""");
		var rooted =
			Read(
				"""{ "version": 1, "targets": { "win-x64": { "executable": "make", "output": "/tmp/elsewhere" } } }""");
		var escapingWorkingDirectory =
			Read(
				"""{ "version": 1, "targets": { "win-x64": { "executable": "make", "output": "out", "workingDirectory": "../.." } } }""");

		Assert.Multiple(() =>
		{
			Assert.That(escaping.FailureReason, Is.EqualTo(PluginBuildFailureReason.BuildConfigInvalid));
			Assert.That(rooted.FailureReason, Is.EqualTo(PluginBuildFailureReason.BuildConfigInvalid));
			Assert.That(escapingWorkingDirectory.FailureReason,
				Is.EqualTo(PluginBuildFailureReason.BuildConfigInvalid));
			Assert.That(escapingWorkingDirectory.FailureMessage, Does.Contain("workingDirectory"));
		});
	}

	[Test]
	public void An_optional_working_directory_is_read_and_an_unknown_property_is_ignored()
	{
		// Unknown properties are ignored so a file written by a newer CLI still builds with an older one.
		var result = Read("""
						  {
						    "version": 1,
						    "somethingAddedLater": { "whatever": true },
						    "targets": {
						      "win-x64": { "executable": "make", "output": "out", "workingDirectory": "src", "extra": 1 }
						    }
						  }
						  """);

		Assert.Multiple(() =>
		{
			Assert.That(result.FailureReason, Is.Null, result.FailureMessage);
			Assert.That(result.Targets!["win-x64"].WorkingDirectory, Is.EqualTo("src"));
		});
	}

	[Test]
	public void A_missing_file_is_an_unreadable_input_and_a_malformed_one_is_an_invalid_subject()
	{
		var missing = PluginBuildConfigReader.Read(Path.Combine(_project, "absent.json"), _project);
		var malformed = Read("{ not json");

		Assert.Multiple(() =>
		{
			// A file that is not there is an environment problem; a file that is there and says nonsense is a
			// defect in the project - the split ExitCode.cs draws.
			Assert.That(missing.FailureReason, Is.EqualTo(PluginBuildFailureReason.BuildConfigNotFound));
			Assert.That(PluginBuildFailureExitCode.For(missing.FailureReason), Is.EqualTo(ExitCode.InputUnreadable));

			Assert.That(malformed.FailureReason, Is.EqualTo(PluginBuildFailureReason.BuildConfigMalformed));
			Assert.That(PluginBuildFailureExitCode.For(malformed.FailureReason), Is.EqualTo(ExitCode.SubjectInvalid));
		});
	}

	private PluginBuildConfigReadResult Read(string json)
	{
		var path = Path.Combine(_project, PluginBuildConfigReader.FileName);
		File.WriteAllText(path, json);

		return PluginBuildConfigReader.Read(path, _project);
	}
}
