using System.Text.Json;
using MacroDeck.Ui.Model.Events;
using MacroDeck.Ui.Model.Negotiation;
using MacroDeck.Ui.Model.Nodes;
using MacroDeck.Ui.Model.Patches;
using MacroDeck.Ui.Model.Resources;
using MacroDeck.Ui.Model.Serialization;
using MacroDeck.Ui.Model.Surfaces;

namespace MacroDeck.Ui.Model.Tests.UnitTests.Serialization;

/// <summary>
/// Compares every wire construct against a hand-written <c>Fixtures/*.json</c> file, byte-for-byte.
/// The fixtures were authored from the rules in the ADR and the issue's own worked example, never
/// generated by running this package's serializer and saving the output - that would only prove the
/// implementation agrees with itself.
/// </summary>
[TestFixture]
public class GoldenSnapshotTests
{
	private static IEnumerable<TestCaseData> Fixtures()
	{
		yield return new TestCaseData("node-minimal", (object)new UiNode { Id = "root", Type = "stack" })
			.SetName("node_minimal");

		yield return new TestCaseData("node-full",
				(object)new UiNode
				{
					Id = "root",
					Type = "chart",
					RequiredComponentVersion = 2,
					Properties = Map(("path", Element("\"M0,0 L1,1\""))),
					Children = [new UiNode { Id = "child", Type = "text" }],
					Fallback = new UiNode { Id = "root-fallback", Type = "text" },
				})
			.SetName("node_full");

		yield return new TestCaseData("tree-config-exclusive",
				(object)new UiTree
				{
					Revision = 1,
					Surface = new UiSurface { Kind = "config", SessionMode = "exclusive" },
					Root = new UiNode { Id = "root", Type = "stack" },
				})
			.SetName("tree_config_exclusive");

		yield return new TestCaseData("tree-widget-shared", (object)WidgetTree()).SetName("tree_widget_shared");

		yield return new TestCaseData("surface-shared",
				(object)new UiSurface { Kind = "config", SessionMode = "shared" })
			.SetName("surface_shared");

		yield return new TestCaseData("surface-exclusive",
				(object)new UiSurface { Kind = "config", SessionMode = "exclusive" })
			.SetName("surface_exclusive");

		yield return new TestCaseData("event-minimal", (object)new UiEvent { NodeId = "submit", Name = "click" })
			.SetName("event_minimal");

		yield return new TestCaseData("event-with-data",
				(object)new UiEvent
				{
					NodeId = "n",
					Name = "change",
					Data = Element("{\"b\":1,\"a\":2}"),
					Revision = 7,
				})
			.SetName("event_with_data");

		yield return new TestCaseData("patch-minimal",
				(object)new UiPatch
				{
					FromRevision = 1,
					ToRevision = 2,
					Operations =
					[
						new UiPatchOperation
						{
							Op = UiPatchOperations.SetProperties,
							NodeId = "title",
							Properties = Map(("text", Element("\"Hello\""))),
						},
					],
				})
			.SetName("patch_minimal");

		yield return new TestCaseData("patch-all-operations", (object)PatchAllOperations())
			.SetName("patch_all_operations");

		yield return new TestCaseData("resource-minimal", (object)new UiResource { ResourceId = "icon-1" })
			.SetName("resource_minimal");

		yield return new TestCaseData("resource-full",
				(object)new UiResource
				{
					ResourceId = "icon-1",
					ContentHash = "sha256:0a1b",
					MediaType = "image/png",
					ByteLength = 2048,
				})
			.SetName("resource_full");

		yield return new TestCaseData("capabilities-everything",
				(object)new UiCapabilities
				{
					UiProtocol = new UiVersionRange { Minimum = 1, Maximum = 1 },
					SupportsAllComponents = true,
				})
			.SetName("capabilities_everything");

		yield return new TestCaseData("capabilities-ranged",
				(object)new UiCapabilities
				{
					UiProtocol = new UiVersionRange { Minimum = 1, Maximum = 1 },
					SupportsAllComponents = false,
					Components = new Dictionary<string, UiVersionRange>
					{
						["chart"] = new() { Minimum = 1, Maximum = 2 },
						["button"] = new() { Minimum = 1, Maximum = 1 },
					},
				})
			.SetName("capabilities_ranged");

		yield return new TestCaseData("properties-key-ordering",
				(object)new UiNode
				{
					Id = "root",
					Type = "t",
					Properties = Map(("b", Element("1")),
						("A", Element("2")),
						("a", Element("3")),
						("B", Element("4")),
						("_x", Element("5")),
						("10", Element("6")),
						("2", Element("7"))),
				})
			.SetName("properties_key_ordering");

		yield return new TestCaseData("numbers-verbatim",
				(object)new UiNode
				{
					Id = "root",
					Type = "t",
					Properties = Map(("a", Element("1.50")),
						("b", Element("1e3")),
						("c", Element("-0.0")),
						("d", Element("1.0")),
						("e", Element("10000000000000000000000"))),
				})
			.SetName("numbers_verbatim");

		yield return new TestCaseData("escaping-and-unicode",
				(object)new UiNode
				{
					Id = "root",
					Type = "t",
					Properties = Map(("text", Element("\"<>&'+`é😀\""))),
				})
			.SetName("escaping_and_unicode");
	}

	[TestCaseSource(nameof(Fixtures))]
	public void Golden_snapshots_match_the_checked_in_bytes(string fixtureName, object value)
	{
		var expected = ReadFixture(fixtureName);

		Assert.Multiple(() =>
		{
			Assert.That(Serialize(value), Is.EqualTo(expected), "Serializing the built object.");

			var roundTripped = DeserializeThenReserialize(value, expected);
			Assert.That(roundTripped, Is.EqualTo(expected), "Deserializing the fixture then re-serializing.");
		});
	}

	/// <summary>
	/// Turns "covers every core construct" into a check that cannot silently rot. Walks every public
	/// instance property reachable from <see cref="UiTree" />, <see cref="UiPatch" />,
	/// <see cref="UiEvent" /> and <see cref="UiCapabilities" /> to find the wire record types a real
	/// tree, patch, event or capabilities payload can contain, then checks that every one of those
	/// types actually appears somewhere in <see cref="Fixtures" />'s object graphs. A namespace sweep
	/// would fail on day one, since <c>UiNegotiationResult</c> and <c>UiPatchOutcome</c> are
	/// computation results that never appear inside a tree, a patch or an event.
	/// </summary>
	[Test]
	public void Every_wire_record_appears_in_at_least_one_golden_fixture()
	{
		var reachable = ReachableWireTypes();
		var covered = CoveredTypes();

		Assert.That(reachable,
			Is.SubsetOf(covered),
			$"Missing from a golden fixture: {string.Join(", ", reachable.Except(covered).Select(t => t.Name))}");
	}

	private static HashSet<Type> ReachableWireTypes()
	{
		var roots = new[] { typeof(UiTree), typeof(UiPatch), typeof(UiEvent), typeof(UiCapabilities) };
		var visited = new HashSet<Type>();
		var queue = new Queue<Type>(roots);

		while (queue.Count > 0)
		{
			var type = queue.Dequeue();
			if (!IsWireRecordType(type) || !visited.Add(type))
			{
				continue;
			}

			foreach (var property in type.GetProperties())
			{
				foreach (var candidate in UnwrapPropertyTypes(property.PropertyType))
				{
					if (IsWireRecordType(candidate))
					{
						queue.Enqueue(candidate);
					}
				}
			}
		}

		return visited;
	}

	private static IEnumerable<Type> UnwrapPropertyTypes(Type propertyType)
	{
		var underlying = Nullable.GetUnderlyingType(propertyType) ?? propertyType;

		if (underlying.IsGenericType)
		{
			foreach (var argument in underlying.GetGenericArguments())
			{
				yield return argument;
			}
		}

		yield return underlying;
	}

	private static bool IsWireRecordType(Type type)
		=> type.Namespace is not null &&
			type.Namespace.StartsWith("MacroDeck.Ui.Model", StringComparison.Ordinal) &&
			type.IsSealed &&
			!type.IsEnum &&
			type != typeof(UiNegotiationResult) &&
			type != typeof(UiPatchOutcome);

	private static HashSet<Type> CoveredTypes()
	{
		var covered = new HashSet<Type>();
		var pending = new Queue<object>(Fixtures().Select(testCase => testCase.Arguments[1]!));

		while (pending.Count > 0)
		{
			var instance = pending.Dequeue();
			var type = instance.GetType();

			if (!IsWireRecordType(type) || !covered.Add(type))
			{
				continue;
			}

			foreach (var property in type.GetProperties())
			{
				var value = property.GetValue(instance);
				foreach (var child in FlattenValues(value))
				{
					pending.Enqueue(child);
				}
			}
		}

		return covered;
	}

	private static IEnumerable<object> FlattenValues(object? value)
	{
		switch (value)
		{
			case null:
				yield break;
			case string or JsonElement:
				yield break;
			case System.Collections.IDictionary dictionary:
				foreach (var entryValue in dictionary.Values)
				{
					if (entryValue is not null)
					{
						yield return entryValue;
					}
				}

				break;
			case System.Collections.IEnumerable enumerable:
				foreach (var item in enumerable)
				{
					if (item is not null)
					{
						yield return item;
					}
				}

				break;
			default:
				yield return value;
				break;
		}
	}

	private static string Serialize(object value) => value switch
	{
		UiNode node => UiCanonicalJson.Serialize(node),
		UiTree tree => UiCanonicalJson.Serialize(tree),
		UiSurface surface => UiCanonicalJson.Serialize(surface),
		UiEvent uiEvent => UiCanonicalJson.Serialize(uiEvent),
		UiPatch patch => UiCanonicalJson.Serialize(patch),
		UiResource resource => UiCanonicalJson.Serialize(resource),
		UiCapabilities capabilities => UiCanonicalJson.Serialize(capabilities),
		_ => throw new ArgumentOutOfRangeException(nameof(value)),
	};

	private static string DeserializeThenReserialize(object value, string json) => value switch
	{
		UiNode => Serialize(JsonSerializer.Deserialize<UiNode>(json, UiCanonicalJson.Options)!),
		UiTree => Serialize(JsonSerializer.Deserialize<UiTree>(json, UiCanonicalJson.Options)!),
		UiSurface => Serialize(JsonSerializer.Deserialize<UiSurface>(json, UiCanonicalJson.Options)!),
		UiEvent => Serialize(JsonSerializer.Deserialize<UiEvent>(json, UiCanonicalJson.Options)!),
		UiPatch => Serialize(JsonSerializer.Deserialize<UiPatch>(json, UiCanonicalJson.Options)!),
		UiResource => Serialize(JsonSerializer.Deserialize<UiResource>(json, UiCanonicalJson.Options)!),
		UiCapabilities => Serialize(JsonSerializer.Deserialize<UiCapabilities>(json, UiCanonicalJson.Options)!),
		_ => throw new ArgumentOutOfRangeException(nameof(value)),
	};

	private static UiTree WidgetTree() => new()
	{
		Revision = 0,
		Surface = new UiSurface { Kind = UiSurfaceKinds.Widget, SessionMode = UiSessionModes.Shared },
		Root = new UiNode
		{
			Id = "canvas",
			Type = "macrodeck.canvas",
			Children =
			[
				new UiNode
				{
					Id = "art",
					Type = "ui.image",
					Properties = Map(("source", UiCanonicalJson.ToElement(new UiResource
						{
							ResourceId = "bg-1",
							MediaType = "image/png",
						})),
						("rotation", Element("37.5"))),
				},
				new UiNode
				{
					Id = "spectrum",
					Type = "ui.chart",
					RequiredComponentVersion = 2,
					Properties = Map(("path", Element("\"M0,0 L10,4\""))),
					Fallback = new UiNode
					{
						Id = "spectrum-fallback",
						Type = "text",
						Properties = Map(("text", Element("\"Spectrum unavailable\""))),
					},
				},
				new UiNode
				{
					Id = "progress",
					Type = "macrodeck.progress",
					Properties = Map(("value", Element("0.42"))),
				},
			],
		},
	};

	private static UiPatch PatchAllOperations() => new()
	{
		FromRevision = 5,
		ToRevision = 6,
		Operations =
		[
			new UiPatchOperation
			{
				Op = UiPatchOperations.SetProperties,
				NodeId = "title",
				Properties = Map(("text", Element("\"Hi\""))),
				RemovedProperties = ["old"],
			},
			new UiPatchOperation
			{
				Op = UiPatchOperations.InsertNode,
				NodeId = "new-item",
				ParentId = "list",
				Index = 2,
				Node = new UiNode { Id = "new-item", Type = "text" },
			},
			new UiPatchOperation { Op = UiPatchOperations.RemoveNode, NodeId = "old-item" },
			new UiPatchOperation
			{
				Op = UiPatchOperations.ReplaceNode,
				NodeId = "header",
				Node = new UiNode { Id = "header", Type = "text" },
			},
			new UiPatchOperation
			{
				Op = UiPatchOperations.MoveNode, NodeId = "item-1", ParentId = "list", Index = 0,
			},
		],
	};

	internal static JsonElement Element(string json) => JsonDocument.Parse(json).RootElement.Clone();

	internal static Dictionary<string, JsonElement> Map(params (string Key, JsonElement Value)[] entries)
	{
		var map = new Dictionary<string, JsonElement>(StringComparer.Ordinal);
		foreach (var (key, value) in entries)
		{
			map[key] = value;
		}

		return map;
	}

	internal static string ReadFixture(string name)
	{
		var path = Path.Combine(AppContext.BaseDirectory, "Fixtures", $"{name}.json");
		return File.ReadAllText(path).TrimEnd('\n');
	}
}
