using System.Text;
using MacroDeck.Localization.Compiler;

namespace MacroDeck.Plugin.Analyzers;

/// <summary>
/// Renders a compiled resource set as the typed C# API plus the catalog data behind it. Kept apart from
/// the generator so the emitter can be exercised on its own, without a compilation.
/// </summary>
internal static class LocalizationSourceEmitter
{
	private const string LocalizedStringType = "global::MacroDeck.Localization.LocalizedString";
	private const string LocalizationKeyType = "global::MacroDeck.Localization.LocalizationKey";
	private const string CatalogInterface = "global::MacroDeck.Localization.ILocalizationCatalog";

	/// <summary>Renders the whole file for one resource set.</summary>
	/// <param name="namespaceName">The namespace to declare, or null/blank for the global namespace.</param>
	/// <param name="className">The generated static class's name.</param>
	/// <param name="result">The compiled resource set.</param>
	public static string Emit(string? namespaceName, string className, LocalizationCompilationResult result)
	{
		var builder = new StringBuilder();
		builder.Append("// <auto-generated/>\n#nullable enable\n\n");

		var indent = string.Empty;
		var hasNamespace = !string.IsNullOrWhiteSpace(namespaceName);

		if (hasNamespace)
		{
			builder.Append("namespace ").Append(namespaceName).Append("\n{\n");
			indent = "\t";
		}

		builder.Append(indent).Append("/// <summary>\n");
		builder.Append(indent).Append("/// The localized strings of <c>").Append(Escape(result.Scope))
			.Append("</c>, generated from its resource files.\n");
		builder.Append(indent).Append("/// </summary>\n");
		builder.Append(indent).Append("public static partial class ").Append(Identifier(className))
			.Append('\n').Append(indent).Append("{\n");

		var body = indent + "\t";

		builder.Append(body).Append("/// <summary>The scope every key below belongs to.</summary>\n");
		builder.Append(body).Append("public const string LocalizationScope = \"").Append(Escape(result.Scope))
			.Append("\";\n\n");

		EmitCatalog(builder, body, result);

		var root = LocalizationKeyTree.Build(result.Entries);
		EmitMembers(builder, body, root);

		builder.Append(indent).Append("}\n");

		if (hasNamespace)
		{
			builder.Append("}\n");
		}

		return builder.ToString();
	}

	private static void EmitCatalog(StringBuilder builder, string indent, LocalizationCompilationResult result)
	{
		builder.Append(indent).Append("/// <summary>\n");
		builder.Append(indent)
			.Append("/// Every culture of this scope's resources, ready to register with the host.\n");
		builder.Append(indent).Append("/// </summary>\n");
		builder.Append(indent).Append("public static ").Append(CatalogInterface)
			.Append(" LocalizationCatalog => _localizationCatalog.Value;\n\n");

		builder.Append(indent).Append("private static readonly global::System.Lazy<").Append(CatalogInterface)
			.Append("> _localizationCatalog = new global::System.Lazy<").Append(CatalogInterface)
			.Append(">(BuildLocalizationCatalog);\n\n");

		builder.Append(indent).Append("private static ").Append(CatalogInterface)
			.Append(" BuildLocalizationCatalog()\n").Append(indent).Append("{\n");

		var body = indent + "\t";
		builder.Append(body)
			.Append("var byCulture = new global::System.Collections.Generic.Dictionary<string, ")
			.Append("global::System.Collections.Generic.IReadOnlyDictionary<string, string>>(")
			.Append(result.Catalog.Count)
			.Append(", global::System.StringComparer.OrdinalIgnoreCase);\n");

		var cultures = new List<string>(result.Catalog.Keys);
		cultures.Sort(StringComparer.Ordinal);

		foreach (var culture in cultures)
		{
			var templates = result.Catalog[culture];
			var keys = new List<string>(templates.Keys);
			keys.Sort(StringComparer.Ordinal);

			builder.Append('\n').Append(body).Append("{\n");
			builder.Append(body).Append("\tvar templates = new global::System.Collections.Generic.")
				.Append("Dictionary<string, string>(").Append(keys.Count)
				.Append(", global::System.StringComparer.Ordinal);\n");

			foreach (var key in keys)
			{
				builder.Append(body).Append("\ttemplates[\"").Append(Escape(key)).Append("\"] = \"")
					.Append(Escape(templates[key])).Append("\";\n");
			}

			builder.Append(body).Append("\tbyCulture[\"").Append(Escape(culture)).Append("\"] = templates;\n");
			builder.Append(body).Append("}\n");
		}

		builder.Append('\n').Append(body)
			.Append("return new global::MacroDeck.Localization.LocalizationCatalog(LocalizationScope, \"")
			.Append(Escape(result.DefaultCulture)).Append("\", byCulture);\n");

		builder.Append(indent).Append("}\n");
	}

	private static void EmitMembers(StringBuilder builder, string indent, LocalizationKeyTree node)
	{
		foreach (var entry in node.Entries)
		{
			builder.Append('\n');
			EmitMethod(builder, indent, entry.Key, entry.Value);
		}

		foreach (var child in node.Children)
		{
			builder.Append('\n').Append(indent).Append("/// <summary>Keys under <c>")
				.Append(Escape(child.Key)).Append("</c>.</summary>\n");
			builder.Append(indent).Append("public static partial class ").Append(Identifier(child.Key))
				.Append('\n').Append(indent).Append("{\n");

			EmitMembers(builder, indent + "\t", child.Value);

			builder.Append(indent).Append("}\n");
		}
	}

	private static void EmitMethod(StringBuilder builder,
		string indent,
		string memberName,
		LocalizationCompiledEntry entry)
	{
		builder.Append(indent).Append("/// <summary>\n");
		builder.Append(indent).Append("/// <c>").Append(EscapeXml(entry.DefaultTemplate)).Append("</c>\n");
		builder.Append(indent).Append("/// </summary>\n");

		foreach (var parameter in entry.Parameters)
		{
			builder.Append(indent).Append("/// <param name=\"").Append(Identifier(parameter.Name))
				.Append("\">Value for <c>{").Append(EscapeXml(parameter.Name)).Append("}</c>.</param>\n");
		}

		if (entry.RemovedGuidance is { Length: > 0 } guidance)
		{
			builder.Append(indent)
				.Append("[global::MacroDeck.Localization.MacroDeckLocalizationRemoved(\"")
				.Append(Escape(guidance)).Append("\")]\n");
		}

		builder.Append(indent).Append("public static ").Append(LocalizedStringType).Append(' ')
			.Append(Identifier(memberName)).Append('(');

		for (var index = 0; index < entry.Parameters.Count; index++)
		{
			if (index > 0)
			{
				builder.Append(", ");
			}

			builder.Append(LocalizationParameterTypes.ToCSharpKeyword(entry.Parameters[index].Type))
				.Append(' ').Append(Identifier(entry.Parameters[index].Name));
		}

		builder.Append(")\n").Append(indent).Append("\t=> new ").Append(LocalizedStringType).Append("(new ")
			.Append(LocalizationKeyType).Append("(LocalizationScope, \"").Append(Escape(entry.Key)).Append("\")");

		if (entry.Parameters.Count == 0)
		{
			builder.Append(");\n");
			return;
		}

		builder.Append(",\n").Append(indent)
			.Append("\t\tnew global::System.Collections.Generic.Dictionary<string, object?>(")
			.Append(entry.Parameters.Count)
			.Append(", global::System.StringComparer.Ordinal)\n").Append(indent).Append("\t\t{\n");

		foreach (var parameter in entry.Parameters)
		{
			builder.Append(indent).Append("\t\t\t[\"").Append(Escape(parameter.Name)).Append("\"] = ")
				.Append(Identifier(parameter.Name)).Append(",\n");
		}

		builder.Append(indent).Append("\t\t});\n");
	}

	private static string Escape(string? value)
	{
		if (string.IsNullOrEmpty(value))
		{
			return string.Empty;
		}

		var builder = new StringBuilder(value!.Length);
		foreach (var character in value)
		{
			switch (character)
			{
				case '\\': builder.Append("\\\\"); break;
				case '"': builder.Append("\\\""); break;
				case '\r': builder.Append("\\r"); break;
				case '\n': builder.Append("\\n"); break;
				case '\t': builder.Append("\\t"); break;
				default: builder.Append(character); break;
			}
		}

		return builder.ToString();
	}

	private static string EscapeXml(string? value)
	{
		if (string.IsNullOrEmpty(value))
		{
			return string.Empty;
		}

		// Onto one line as well as XML-escaped: a doc comment is a run of `///` lines, so a resource value
		// that spans lines would put its continuation into the file as code.
		return value!.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;")
			.Replace("\r\n", " ").Replace('\r', ' ').Replace('\n', ' ');
	}

	/// <summary>Turns a key segment into a usable C# identifier. Characters an identifier cannot carry
	/// become underscores, and a segment colliding with a keyword is escaped rather than renamed, so the
	/// member keeps the name the resource author chose.</summary>
	internal static string Identifier(string name)
	{
		if (string.IsNullOrEmpty(name))
		{
			return "_";
		}

		var builder = new StringBuilder(name.Length);
		var first = name[0];
		builder.Append(first == '_' || char.IsLetter(first) ? first : '_');

		for (var index = 1; index < name.Length; index++)
		{
			var character = name[index];
			builder.Append(character == '_' || char.IsLetterOrDigit(character) ? character : '_');
		}

		var identifier = builder.ToString();
		return LocalizationKeywords.IsKeyword(identifier) ? "@" + identifier : identifier;
	}
}
