using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MacroDeck.Plugin.Analyzers;

/// <summary>
/// Emits <c>[assembly: MacroDeckSdkUsage(...)]</c> recording which deprecated SDK APIs the compiled
/// plugin actually references, so the host can tell "uses a deprecated API" from "was built against an
/// SDK in which something is deprecated" - see issue #418's rule that an inference must never be
/// presented as confirmed usage.
///
/// <para>
/// A generator rather than an MSBuild target because only the compiler knows which APIs are referenced;
/// a target could re-read the SDK version and nothing more, which is exactly the inference this replaces.
/// A generated attribute rather than an embedded resource because a generator cannot emit resources -
/// and because deriving the manifest from the same semantic model that raises MDP5002 means the two can
/// never disagree.
/// </para>
///
/// <para>
/// Nothing is emitted for a compilation that does not reference <c>MacroDeck.Sdk</c>, or for the SDK's own
/// assemblies. Absence is meaningful downstream: a plugin with no attribute is classified <c>inferred</c>
/// or <c>unknown</c>, never <c>confirmed</c>.
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SdkUsageManifestGenerator : IIncrementalGenerator
{
	/// <summary>
	/// Mirrors <c>ProtocolLimits.MaxReportedDeprecatedApis</c>. Duplicated rather than referenced: this
	/// assembly targets netstandard2.0 and cannot reference the net10.0 protocol package. The two are
	/// pinned together by a test.
	/// </summary>
	internal const int MaxReportedApis = 64;

	/// <summary>Mirrors <c>ProtocolLimits.MaxDeprecatedApiIdLength</c> - see <see cref="MaxReportedApis" />.</summary>
	internal const int MaxApiIdLength = 256;

	private const string SdkAssemblyName = "MacroDeck.Sdk";

	private static readonly ImmutableHashSet<string> _sdkAssemblyNames = ImmutableHashSet.Create(SdkAssemblyName,
		"MacroDeck.Plugin.Hosting",
		"MacroDeck.Plugin.Protocol",
		"MacroDeck.Plugin.Analyzers");

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var usages = context.SyntaxProvider
			.CreateSyntaxProvider(static (node, _) => node is SimpleNameSyntax,
				static (syntaxContext, _)
					=> DeprecatedApiId(syntaxContext))
			.Where(static apiId => apiId is not null)
			.Collect();

		context.RegisterSourceOutput(context.CompilationProvider.Combine(usages),
			static (sourceContext, source) => Emit(sourceContext, source.Left, source.Right!));
	}

	/// <summary>
	/// The documentation comment id of the deprecated API this node references, or null. The containing
	/// type is checked as well as the member, so reaching a deprecated type through a member that is not
	/// itself deprecated still counts as using it.
	/// </summary>
	private static string? DeprecatedApiId(GeneratorSyntaxContext context)
	{
		var symbol = context.SemanticModel.GetSymbolInfo(context.Node).Symbol;

		if (symbol is null)
		{
			return null;
		}

		if (DeprecationMetadata.TryRead(symbol, out _))
		{
			return symbol.OriginalDefinition.GetDocumentationCommentId();
		}

		return symbol.ContainingType is not null && DeprecationMetadata.TryRead(symbol.ContainingType, out _)
			? symbol.ContainingType.OriginalDefinition.GetDocumentationCommentId()
			: null;
	}

	private static void Emit(SourceProductionContext context, Compilation compilation, ImmutableArray<string?> apiIds)
	{
		var sdkVersion = compilation.SourceModule.ReferencedAssemblySymbols
			.FirstOrDefault(assembly => assembly.Name == SdkAssemblyName)
			?.Identity.Version;

		// No SDK reference means no plugin, and the attribute type would not resolve anyway. The SDK's
		// own assemblies are skipped for the same reason a manifest of one's own surface says nothing.
		if (sdkVersion is null || _sdkAssemblyNames.Contains(compilation.AssemblyName ?? string.Empty))
		{
			return;
		}

		var distinct = apiIds
			.Where(id => id is { Length: > 0 } && id.Length <= MaxApiIdLength)
			.Distinct(StringComparer.Ordinal)
			.OrderBy(id => id, StringComparer.Ordinal)
			.ToList();

		var truncated = distinct.Count > MaxReportedApis;
		var reported = truncated ? distinct.Take(MaxReportedApis) : distinct;

		context.AddSource("MacroDeckSdkUsage.g.cs",
			SourceText.From(Render(sdkVersion.ToString(), reported, truncated),
				Encoding.UTF8));
	}

	private static string Render(string sdkVersion, IEnumerable<string?> apiIds, bool truncated)
	{
		var entries = string.Join(", ", apiIds.Select(id => $"\"{id}\""));

		return $$"""
				 // <auto-generated/>
				 // Emitted by MacroDeck.Plugin.Analyzers. Records which deprecated Macro Deck SDK APIs this
				 // assembly references, so the host can report confirmed usage instead of inferring from a
				 // version number. Removing the analyzer package removes this, and the host falls back to
				 // inferring from the SDK version alone.
				 [assembly: global::MacroDeck.Sdk.Deprecation.MacroDeckSdkUsageAttribute(
				 	"{{sdkVersion}}",
				 	new string[] { {{entries}} },
				 	Truncated = {{(truncated ? "true" : "false")}})]

				 """;
	}
}
