import { strict as assert } from 'node:assert';
import { mkdirSync, mkdtempSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { test } from 'node:test';

import { RUNTIME, assertRuntimeCommit, generateNotices, parseRuntimeVersion } from './appimage-library-notices.mjs';

const MULTIARCH = 'x86_64-linux-gnu';
const LGPL = 'GNU LESSER GENERAL PUBLIC LICENSE\nVersion 2.1, February 1999\n';
const OS_RELEASE = 'NAME="Ubuntu"\nVERSION_ID="22.04"\nPRETTY_NAME="Ubuntu 22.04.5 LTS"\nID=ubuntu\n';

function appDir(files, links = {}) {
	const root = mkdtempSync(join(tmpdir(), 'appdir-'));
	const all = {
		'usr/share/applications/Macro Deck.desktop': '[Desktop Entry]\nName=Macro Deck\nExec=MacroDeck\nIcon=MacroDeck\n',
		'usr/bin/MacroDeck': 'app',
		'Macro Deck.png': 'png',
		'usr/share/icons/hicolor/128x128/apps/MacroDeck.png': 'png',
		'usr/lib/Macro Deck/host/MacroDeckHost.dll': 'host',
		AppRun: '#! /usr/bin/env bash\n\n# autogenerated by linuxdeploy\n',
		'apprun-hooks/linuxdeploy-plugin-gtk.sh': '#! /usr/bin/env bash\n',
		...files
	};
	for (const [rel, content] of Object.entries(all)) {
		mkdirSync(dirname(join(root, rel)), { recursive: true });
		writeFileSync(join(root, rel), content);
	}
	symlinkSync('usr/share/applications/Macro Deck.desktop', join(root, 'Macro Deck.desktop'));
	for (const [rel, target] of Object.entries(links)) {
		mkdirSync(dirname(join(root, rel)), { recursive: true });
		symlinkSync(target, join(root, rel));
	}
	return root;
}

// An Ubuntu 22.04 build machine: merged /usr, so dpkg may record a library under /lib while it lives in /usr/lib.
function machine({ files = {}, owners = {}, packages = {}, archives = {} }) {
	const realpaths = new Map();
	for (const [path, real] of Object.entries(files)) {
		realpaths.set(path, real);
		realpaths.set(real, real);
	}
	const texts = {
		'/usr/share/common-licenses/LGPL-2.1': LGPL,
		'/etc/os-release': OS_RELEASE,
		...Object.fromEntries(
			Object.entries(packages)
				.filter(([, info]) => info.copyright)
				.map(([pkg, info]) => [`/usr/share/doc/${pkg.replace(/:.*/, '')}/copyright`, info.copyright])
		)
	};
	return {
		multiarch: MULTIARCH,
		system: {
			realpath: path => realpaths.get(path) ?? null,
			readFile: path => texts[path] ?? null
		},
		dpkg: {
			search(pattern) {
				const matches = pattern.startsWith('*/')
					? Object.keys(owners).filter(path => path.endsWith(pattern.slice(1)))
					: Object.keys(owners).filter(path => path === pattern);
				return matches.map(path => ({ packages: owners[path], path }));
			},
			info: pkg => packages[pkg],
			packagedFile: async (pkg, path) => archives[pkg]?.[path] ?? null
		}
	};
}

const LIBFOO = {
	files: { '/usr/lib/x86_64-linux-gnu/libfoo.so.1': '/usr/lib/x86_64-linux-gnu/libfoo.so.1.2.3' },
	owners: { '/lib/x86_64-linux-gnu/libfoo.so.1.2.3': ['libfoo1:amd64'] },
	packages: {
		'libfoo1:amd64': { version: '1.2.3-1ubuntu1', source: 'foo', sourceVersion: '1.2.3-1ubuntu1', copyright: 'Copyright 2020 Foo Authors\nLicense: LGPL-2.1+\n' }
	}
};

test('attributes a flattened library to the package that owns its system file under merged /usr', async () => {
	const root = appDir({ 'usr/lib/libfoo.so.1': 'elf' });

	const { text } = await generateNotices(root, machine(LIBFOO));

	assert.match(text, /Ubuntu 22\.04\.5 LTS/);
	assert.match(text, /Ubuntu archive/);
	assert.match(text, /Package: libfoo1 1\.2\.3-1ubuntu1\nSource package: foo 1\.2\.3-1ubuntu1\n/);
	assert.match(text, /Source code: https:\/\/launchpad\.net\/ubuntu\/\+source\/foo\/1\.2\.3-1ubuntu1\n/);
	assert.match(text, /Files:\n  usr\/lib\/libfoo\.so\.1\n/);
	assert.ok(text.includes('Copyright 2020 Foo Authors\nLicense: LGPL-2.1+'), 'copyright file reproduced verbatim');
});

test('attributes helpers in library subdirectories and data files from Ubuntu packages', async () => {
	const root = appDir({
		'usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKitWebProcess': 'elf',
		'usr/share/glib-2.0/schemas/org.gtk.Settings.Debug.gschema.xml': '<schemalist/>'
	});
	const env = machine({
		files: {
			'/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKitWebProcess': '/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKitWebProcess',
			'/usr/share/glib-2.0/schemas/org.gtk.Settings.Debug.gschema.xml': '/usr/share/glib-2.0/schemas/org.gtk.Settings.Debug.gschema.xml'
		},
		owners: {
			'/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKitWebProcess': ['libwebkit2gtk-4.1-0:amd64'],
			'/usr/share/glib-2.0/schemas/org.gtk.Settings.Debug.gschema.xml': ['libgtk-3-common']
		},
		packages: {
			'libwebkit2gtk-4.1-0:amd64': { version: '2.50.4', source: 'webkit2gtk', sourceVersion: '2.50.4', copyright: 'WebKit copyright' },
			'libgtk-3-common': { version: '3.24.33', source: 'gtk+3.0', sourceVersion: '3.24.33', copyright: 'GTK copyright' }
		}
	});

	const { packages } = await generateNotices(root, env);

	assert.deepEqual(
		packages.map(p => [p.name, p.files]),
		[
			['libgtk-3-common', ['usr/share/glib-2.0/schemas/org.gtk.Settings.Debug.gschema.xml']],
			['libwebkit2gtk-4.1-0', ['usr/lib/x86_64-linux-gnu/webkit2gtk-4.1/WebKitWebProcess']]
		]
	);
});

test('attributes GTK modules, pixbuf loaders and typelibs that linuxdeploy moved out of the multiarch directory', async () => {
	const root = appDir({
		'usr/lib/gtk-3.0/3.0.0/immodules/im-wayland.so': 'elf',
		'usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so': 'elf',
		'usr/lib/girepository-1.0/Atk-1.0.typelib': 'typelib'
	});
	const system = [
		'/usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so',
		'/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so',
		'/usr/lib/x86_64-linux-gnu/girepository-1.0/Atk-1.0.typelib'
	];
	const env = machine({
		files: Object.fromEntries(system.map(path => [path, path])),
		owners: {
			[system[0]]: ['libgtk-3-0:amd64'],
			[system[1]]: ['librsvg2-common:amd64'],
			[system[2]]: ['gir1.2-atk-1.0:amd64']
		},
		packages: {
			'libgtk-3-0:amd64': { version: '3.24.33', source: 'gtk+3.0', sourceVersion: '3.24.33', copyright: 'GTK copyright' },
			'librsvg2-common:amd64': { version: '2.52.5', source: 'librsvg', sourceVersion: '2.52.5', copyright: 'librsvg copyright' },
			'gir1.2-atk-1.0:amd64': { version: '2.36.0', source: 'atk1.0', sourceVersion: '2.36.0', copyright: 'ATK copyright' }
		}
	});

	const { packages } = await generateNotices(root, env);

	assert.deepEqual(
		packages.map(p => [p.name, p.files]),
		[
			['gir1.2-atk-1.0', ['usr/lib/girepository-1.0/Atk-1.0.typelib']],
			['libgtk-3-0', ['usr/lib/gtk-3.0/3.0.0/immodules/im-wayland.so']],
			['librsvg2-common', ['usr/lib/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so']]
		]
	);
});

test('reproduces the copyright from the package archive when the build machine has no /usr/share/doc', async () => {
	const root = appDir({ 'usr/lib/libfoo.so.1': 'elf' });
	const env = machine({
		...LIBFOO,
		packages: { 'libfoo1:amd64': { ...LIBFOO.packages['libfoo1:amd64'], copyright: null } },
		archives: { 'libfoo1:amd64': { '/usr/share/doc/libfoo1/copyright': 'Copyright 2020 Foo Authors, from the .deb\n' } }
	});

	const { text } = await generateNotices(root, env);

	assert.ok(text.includes('Copyright 2020 Foo Authors, from the .deb'));
});

test('fails when a package copyright is neither installed nor in its archive', async () => {
	const root = appDir({ 'usr/lib/libfoo.so.1': 'elf' });
	const env = machine({ ...LIBFOO, packages: { 'libfoo1:amd64': { ...LIBFOO.packages['libfoo1:amd64'], copyright: null } } });

	await assert.rejects(generateNotices(root, env), /libfoo1:amd64: \/usr\/share\/doc\/libfoo1\/copyright is missing/);
});

test('does not attribute the app binary, its icons, desktop entry, host tree or in-AppDir symlinks', async () => {
	const root = appDir({}, { 'usr/lib/libfoo-link.so': 'x86_64-linux-gnu/missing.so' });

	const { packages, generated } = await generateNotices(root, machine({}));

	assert.deepEqual(packages, []);
	assert.deepEqual(generated, []);
});

test('lists generated caches that no package owns instead of failing', async () => {
	const root = appDir({ 'usr/share/glib-2.0/schemas/gschemas.compiled': 'gvariant' });
	const env = machine({ files: { '/usr/share/glib-2.0/schemas/gschemas.compiled': '/usr/share/glib-2.0/schemas/gschemas.compiled' } });

	const { text, generated } = await generateNotices(root, env);

	assert.deepEqual(generated, ['usr/share/glib-2.0/schemas/gschemas.compiled']);
	assert.match(text, /Generated files[\s\S]*usr\/share\/glib-2\.0\/schemas\/gschemas\.compiled/);
});

test('fails naming every file that no Ubuntu package owns', async () => {
	const root = appDir({ 'usr/lib/libmystery.so': 'elf', 'usr/share/mystery/data.xml': 'xml' });
	const env = machine({ files: { '/usr/share/mystery/data.xml': '/usr/share/mystery/data.xml' } });

	await assert.rejects(generateNotices(root, env), error => {
		assert.match(error.message, /usr\/lib\/libmystery\.so/);
		assert.match(error.message, /usr\/share\/mystery\/data\.xml: no Ubuntu package owns/);
		return true;
	});
});

test('fails when a file maps to system files of different packages', async () => {
	const root = appDir({ 'usr/lib/libdup.so.1': 'elf' });
	const env = machine({
		files: { '/usr/lib/libdup.so.1': '/usr/lib/libdup.so.1', '/usr/lib/x86_64-linux-gnu/libdup.so.1': '/usr/lib/x86_64-linux-gnu/libdup.so.1' },
		owners: { '/usr/lib/libdup.so.1': ['libdup-a'], '/usr/lib/x86_64-linux-gnu/libdup.so.1': ['libdup-b'] }
	});

	await assert.rejects(generateNotices(root, env), /usr\/lib\/libdup\.so\.1: ambiguous/);
});

test('treats a flattened copy of a host library as part of the host', async () => {
	const root = appDir({
		'usr/lib/libmscordaccore.so': 'elf',
		'usr/lib/Macro Deck/host/runtime/shared/Microsoft.NETCore.App/10.0.0/libmscordaccore.so': 'elf'
	});

	// PowerShell on the runner ships its own libmscordaccore.so, which must not claim the host's copy.
	const env = machine({ owners: { '/opt/microsoft/powershell/7/libmscordaccore.so': ['powershell'] } });
	env.system.realpath = path => (path === '/opt/microsoft/powershell/7/libmscordaccore.so' ? path : null);

	const { text, packages } = await generateNotices(root, env);

	assert.deepEqual(packages, []);
	assert.match(text, /Copies of Macro Deck host files[\s\S]*usr\/lib\/libmscordaccore\.so/);
});

test('fails on an AppRun hook nobody reviewed', async () => {
	const root = appDir({ 'apprun-hooks/linuxdeploy-plugin-qt-hook.sh': '#!/bin/sh\n' });

	await assert.rejects(generateNotices(root, machine({})), /apprun-hooks\/linuxdeploy-plugin-qt-hook\.sh: unknown AppRun hook/);
});

test('refuses to attribute libraries on a system that is not Ubuntu', async () => {
	const root = appDir({});
	const env = machine({});
	const readFile = env.system.readFile;
	env.system.readFile = path => (path === '/etc/os-release' ? 'ID=fedora\n' : readFile(path));

	await assert.rejects(generateNotices(root, env), /must be built on Ubuntu/);
});

test('names the pinned runtime, its source tree and libfuse with the full LGPL text', async () => {
	const { text } = await generateNotices(appDir({}), machine({}));

	assert.ok(text.includes(`https://github.com/AppImage/type2-runtime/tree/${RUNTIME.fullCommit}`));
	assert.match(text, /libfuse 3\.15\.0, statically linked into the runtime\nLicense: LGPL-2\.1/);
	assert.ok(text.includes(LGPL.trimEnd()), 'LGPL-2.1 text reproduced');
	for (const component of ['musl libc', 'squashfuse', 'Zstandard', 'zlib', 'mimalloc']) {
		assert.ok(text.includes(`${component} `), `${component} listed`);
	}
	assert.match(text, /linuxdeploy AppRun script[\s\S]*License: MIT/);
	assert.match(text, /linuxdeploy-plugin-gtk AppRun hook/);
});

test('reads the runtime commit the type2 runtime prints for --appimage-version', () => {
	const stderr = 'AppImage runtime version: https://github.com/AppImage/type2-runtime/commit/dd6cebe\n';

	assert.equal(parseRuntimeVersion(stderr), 'dd6cebe');
	assert.throws(() => parseRuntimeVersion('Usage: ...'), /could not read the AppImage runtime version/);
});

test('a runtime with a different commit than the reviewed one fails with a review instruction', () => {
	assert.doesNotThrow(() => assertRuntimeCommit(RUNTIME.commit, 'runtime-x86_64'));
	assert.throws(() => assertRuntimeCommit('75849dc', 'Macro Deck.AppImage'), error => {
		assert.match(error.message, /75849dc/);
		assert.match(error.message, /Review the LICENSE and build files/);
		return true;
	});
});
