// Mirrored from ui-model/src/MacroDeck.Ui/Config/UiConfigPrimitives.cs, same declaration order.
// No isKnown on purpose: the vocabulary is open, and an unrecognised type degrades to the node's
// fallback rather than being rejected.
export const UiConfigPrimitives = {
  String: 'string',
  Number: 'number',
  Boolean: 'boolean',
  Choice: 'choice',
  Password: 'password',
  Secret: 'secret',
  DynamicChoice: 'dynamic-choice',
  Autocomplete: 'autocomplete',
  MultiSelect: 'multiselect',
  Color: 'color',
  File: 'file',
  Folder: 'folder',
  Hotkey: 'hotkey',
  Duration: 'duration',
  DateTime: 'datetime',
  Json: 'json',
  Code: 'code',
  KeyValue: 'keyvalue',
  Object: 'object',
  Array: 'array',
  IpAddress: 'ipaddress',
  Url: 'url',
  Icon: 'icon',
  Image: 'image',
  KeyboardSequence: 'keyboard-sequence',
  KeyboardCombo: 'keyboard-combo',
  WidgetTarget: 'widget-target',
  ActionsListEditor: 'actions-list-editor',
  ActionPicker: 'action-picker',
  VariablePicker: 'variable-picker',
  DevicePicker: 'device-picker',
  IntegrationPicker: 'integration-picker',
  IconDisplay: 'icon-display',
  StateMappingEditor: 'state-mapping-editor',
  Flow: 'flow',
  Step: 'step',
  Stack: 'stack',
  Tabs: 'tabs',
  Tab: 'tab',
  Heading: 'heading',
  Prose: 'prose',
  Instructions: 'instructions',
  Instruction: 'instruction',
  CopyValue: 'copy-value',
  Link: 'link',
  AdvancedSection: 'advanced-section',
  Divider: 'divider',
  Banner: 'banner',
  ValidationMessage: 'validation-message',
  Busy: 'busy',
  Button: 'button',
  WidgetConfiguration: 'widget-configuration',
  WidgetProperties: 'widget-properties',
  WidgetEditor: 'widget-editor',
} as const;

export const UI_CONFIG_PRIMITIVES_WELL_KNOWN: readonly string[] = [
  UiConfigPrimitives.String, UiConfigPrimitives.Number, UiConfigPrimitives.Boolean, UiConfigPrimitives.Choice,
  UiConfigPrimitives.Password, UiConfigPrimitives.Secret, UiConfigPrimitives.DynamicChoice,
  UiConfigPrimitives.Autocomplete, UiConfigPrimitives.MultiSelect, UiConfigPrimitives.Color,
  UiConfigPrimitives.File, UiConfigPrimitives.Folder, UiConfigPrimitives.Hotkey, UiConfigPrimitives.Duration,
  UiConfigPrimitives.DateTime, UiConfigPrimitives.Json, UiConfigPrimitives.Code, UiConfigPrimitives.KeyValue,
  UiConfigPrimitives.Object, UiConfigPrimitives.Array, UiConfigPrimitives.IpAddress, UiConfigPrimitives.Url,
  UiConfigPrimitives.Icon, UiConfigPrimitives.Image, UiConfigPrimitives.KeyboardSequence,
  UiConfigPrimitives.KeyboardCombo, UiConfigPrimitives.WidgetTarget, UiConfigPrimitives.ActionsListEditor,
  UiConfigPrimitives.ActionPicker, UiConfigPrimitives.VariablePicker, UiConfigPrimitives.DevicePicker,
  UiConfigPrimitives.IntegrationPicker, UiConfigPrimitives.IconDisplay,
  UiConfigPrimitives.StateMappingEditor,
  UiConfigPrimitives.Flow, UiConfigPrimitives.Step, UiConfigPrimitives.Stack, UiConfigPrimitives.Tabs,
  UiConfigPrimitives.Tab, UiConfigPrimitives.Heading, UiConfigPrimitives.Prose,
  UiConfigPrimitives.Instructions, UiConfigPrimitives.Instruction, UiConfigPrimitives.CopyValue,
  UiConfigPrimitives.Link, UiConfigPrimitives.AdvancedSection, UiConfigPrimitives.Divider,
  UiConfigPrimitives.Banner, UiConfigPrimitives.ValidationMessage, UiConfigPrimitives.Busy, UiConfigPrimitives.Button,
  UiConfigPrimitives.WidgetConfiguration, UiConfigPrimitives.WidgetProperties,
  UiConfigPrimitives.WidgetEditor,
];
