<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="YamlDotNet" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="MacroDeck.LicenseTool.Tests.UnitTests" />
    </ItemGroup>

</Project>
