// Deck, widget and profile models, and the pure logic over them
export {
  type ActionBlock,
  type ActionBlockDefinition,
  type ActionBlockParameter,
  type ActionBlockType,
  type ActionBranch,
  type ActionFlow,
  type ActionParamControlType,
  type ComparisonExpression,
  type ComparisonOperator,
  type ConditionExpression,
  EVENT_TRIGGER_TYPE,
  eventConfigurationValues,
  type EventReference,
  type EventTriggerBinding,
  type HotkeyValue,
  isComparisonExpression,
  isEventFlow,
  isEventReference,
  isHotkeyValue,
  isLogicalExpression,
  isSameTriggerType,
  isSecretReference,
  isStateOperator,
  isVariableReference,
  isWidgetAppearanceActionId,
  type LogicalExpression,
  type ParameterValue,
  qualifiedEventId,
  type SecretReference,
  type VariableReference,
  WIDGET_APPEARANCE_ACTION_IDS,
  WIDGET_APPEARANCE_RESET,
  WIDGET_INTEGRATION_ID,
  WIDGET_TARGET_SELF,
} from './domain/action-builder.interface';
export {
  cloneBlockWithNewIds,
  collectListIds,
  collectSecretIds,
  containsBlock,
  createBlockFromDefinition,
  defaultParameterValue,
  descendantLists,
  findBlock,
  generateBlockId,
  hydrateBlockParameters,
  insertAfterBlock,
  insertBlockAt,
  isInvalidNestedMove,
  isListInsideLoop,
  mapDescendants,
  mapSecretReferences,
  normalizeLegacyParamTypes,
  removeBlockAt,
  removeBlockFromFlows,
  resolveList,
} from './domain/action-flow.util';
export {
  BACKUP_COMPONENT_GROUP_IDS,
  type BackupComponentGroup,
  type BackupComponentGroupLabel,
  backupComponentGroupLabel,
  backupComponentGroupLabels,
  type BackupDependencyWarning,
  backupDependencyWarningMessage,
  type BackupTranslator,
} from './domain/backup-component-groups';
export {
  createPendingStateLabelVariable,
  createPendingStateVariable,
  STATE_LABEL_VARIABLE_NAME,
  STATE_VARIABLE_NAME,
} from './domain/button-state-variable.util';
export {
  adoptProvidedStates,
  createStateId,
  DEFAULT_OFF_STATE_ID,
  DEFAULT_ON_STATE_ID,
  defaultStateDefinitions,
  findState,
  findStateIndex,
  isEffectiveMapping,
  isValidStateId,
  normalizeStates,
  type ProvidedState,
  type ProvidedStateAppearance,
  resolveActiveStateId,
} from './domain/button-state.util';
export {
  appendComparison,
  appendGroup,
  collectComparisons,
  createComparison,
  createEmptyComparison,
  createLogical,
  flatten,
  flipConnectiveAt,
  removeOperand,
  replaceOperand,
} from './domain/condition-expression.util';
export {
  findFlowForTrigger,
  type LocalDeckNavigation,
  resolveLocalDeckNavigation,
} from './domain/deck-navigation.util';
export {
  defaultEventConfigurationValue,
  type EventDefinition,
  type EventDefinitionDto,
  eventPayloadVariables,
  type EventProviderGroup,
  type GetEventDefinitionsResponse,
  groupEventsByProvider,
  isEventFilterParameter,
  normalizeEventTriggerNames,
  resolveEventPayloadParameter,
} from './domain/event-definition.interface';
export {
  type Folder,
  type FolderContextMenu,
  type FolderDragState,
  type FolderDropPosition,
  type FolderMoveDirection,
  type FolderMoveRequest,
  isWidgetGridView,
  WIDGET_GRID_VIEW_ID,
} from './domain/folder.interface';
export { iconDisplayStyle, momentaryIcon, resolveIconDisplay } from './domain/icon-display.util';
export {
  collectIconPrefetchTargets,
  type IconPrefetchMetrics,
  type IconPrefetchTarget,
  iconSizeBucket,
  widgetIconZoomFactor,
} from './domain/icon-prefetch.util';
export {
  type DelayStepValue,
  formatCombo,
  isApplePlatform,
  isSelectionModifierEvent,
  KEYBOARD_MODIFIERS,
  type KeyboardComboValue,
  type KeyboardSequenceValue,
  type KeyboardStepType,
  type KeyboardStepValue,
  type KeyboardTranslator,
  type KeyComboStepValue,
  type KeyDownStepValue,
  keyFromEvent,
  type KeyGroup,
  type KeyOption,
  type KeyUpStepValue,
  metaKeyLabel,
  modifierLabel,
  supportedKeyGroups,
  type TextStepValue,
} from './domain/keyboard.interface';
export { containsLiquid } from './domain/liquid.util';
export { collectDisplayedWidgets, foreignPinnedWidgets } from './domain/pinned-widget.util';
export {
  type Profile,
  type ProfileLayout,
  type ProfileLayoutCompatibility,
  type ProfileLayoutCompatibilityStatus,
  type ProfileLayoutConstraint,
} from './domain/profile.interface';
export {
  isRunScriptWidgetTargetParam,
  isScriptInputParam,
  normalizeScriptInputs,
  parseScriptInputsMetadata,
  RUN_SCRIPT_WIDGET_PARAM,
  SCRIPT_CALL_SITES,
  SCRIPT_INPUT_PARAM_PREFIX,
  SCRIPT_INPUTS_METADATA_KEY,
  SCRIPT_RUNS_ON_WIDGET_METADATA_KEY,
  scriptInputControlType,
  scriptInputDefaultValue,
  scriptInputNameFromParam,
  scriptInputParameter,
  scriptInputParamName,
  type ScriptInputValue,
  scriptInputVariables,
} from './domain/script-input.util';
export {
  type Script,
  SCRIPT_TRIGGER_TYPE,
  scriptActionCount,
  scriptFlow,
  type ScriptInput,
  type ScriptInputType,
  type ScriptUsage,
} from './domain/script.interface';
export {
  buildProposedName,
  collectUserAgentInfo,
  parseBrowser,
  parseFormFactor,
  parsePlatform,
  type UaFormFactor,
  type UserAgentDataLike,
  type UserAgentInfo,
} from './domain/user-agent.util';
export {
  findVariableTokenTrigger,
  hasVariableToken,
  matchesVariableTokenQuery,
  parseVariableSegments,
  soleVariableToken,
  type VariableTextSegment,
  type VariableTokenKind,
  variableTokenKind,
  variableTokenLabel,
  variableTokenPattern,
  type VariableTokenSegment,
  variableTokenText,
  type VariableTokenTrigger,
  type VariableValueSegment,
} from './domain/variable-token.util';
export {
  type Variable,
  type VariableClassification,
  type VariableScope,
  type VariableType,
} from './domain/variable.interface';
export { type WidgetClipboardEntry } from './domain/widget-clipboard-entry';
export {
  ICON_PACK_ICON_TYPE,
  iconPackRef,
  iconPackReferenceOf,
  isIconPackRef,
  readWidgetIconRef,
  type WidgetIconRef,
} from './domain/widget-icon-ref.util';
export {
  DEFAULT_WIDGET_RENDER_STATE,
  type WidgetGridMode,
  type WidgetRenderState,
} from './domain/widget-render-state';
export {
  defaultWidgetData,
  fromEditorJson,
  parseWidgetData,
  serializeWidgetData,
  toEditorJson,
} from './domain/widget-serialization';
export {
  type ActionButtonData,
  type ActionButtonTriggerType,
  BORDER_ANIMATION_PERIOD_MS,
  BUILT_IN_WIDGET_TYPES,
  type ButtonState,
  type ButtonStateDefinition,
  type ButtonStateMapping,
  type ButtonStateMappingRule,
  type ButtonStateProvider,
  type CellDimensions,
  type ClockData,
  type ClockDateFormat,
  type ClockDatePosition,
  type ClockHourCycle,
  type ClockStyle,
  COLOR_WIDGET_BORDER_STYLES,
  DEFAULT_BUTTON_BACKGROUND_COLOR,
  DEFAULT_ICON_DISPLAY,
  DEFAULT_SLIDER_COLOR,
  DEFAULT_WIDGET_BORDER_COLOR,
  type GridDimensions,
  type GridWidget,
  type HistoryGraphData,
  ICON_DISPLAY_LIMITS,
  type ManualStateBackup,
  type MusicPlayerCoverStyle,
  type MusicPlayerData,
  type PinScope,
  type ResolvedWidgetBorder,
  resolveWidgetBorder,
  type SliderData,
  type WeatherData,
  WIDGET_BORDER_WIDTH,
  WIDGET_REFERENCE_BORDER_RADIUS,
  WIDGET_REFERENCE_CELL_SIZE,
  WIDGET_REFERENCE_GAP,
  type WidgetBorder,
  type WidgetBorderStyle,
  type WidgetData,
  type WidgetIconDisplay,
  type WidgetIconFit,
  type WidgetIconProvider,
  WidgetType,
} from './domain/widget.interface';

// The grid layout engine
export {
  canPlaceGroup,
  cellFromPoint,
  clampRectToGrid,
  clampSizeToGrid,
  computeCellDimensions,
  computePasteRect,
  DEFAULT_CELL_GAP_RATIO,
  type GridPlacement,
  type GridRect,
  rectsEqual,
  rectsOverlap,
  reflowLayout,
  type ReflowResult,
  snapDrag,
  snapGroupDelta,
  snapResize,
  validateGroupMove,
  widgetAspectRatio,
} from './grid/grid-layout.util';
export {
  cellOffset,
  contentScaleFor,
  DEFAULT_GRID_GEOMETRY,
  type GridGeometry,
  GridMetrics,
  isCellOccupied,
  spanSize,
} from './grid/grid-metrics';

export {
  type FolderGridSettings,
  type ProfileGridDefaults,
  type ResolvedFolderGrid,
  resolveFolderGrid,
} from './grid/folder-grid';

// The Macro Deck UI model
export {
  isComponentProfileType,
  negotiateComponent,
  UI_CONFIG_RENDER_CAPABILITIES,
  type UiComponentRange,
} from './ui-framework/ui-capabilities';
export { applyConfigDraftEvent, composeConfigDraft } from './ui-config/config-draft.util';
export { UiConfigEntryPoints } from './ui-config/config-entry-points';
export { UiConfigEvents } from './ui-config/config-events';
export { UI_CONFIG_PRIMITIVES_WELL_KNOWN, UiConfigPrimitives } from './ui-config/config-primitives';
export { UiConfigProperties, type UiNodeOption } from './ui-config/config-properties';
export { supportsUiModelVersion, UiModelVersions } from './ui-framework/ui-model-version';
export {
  emitsEvent,
  nodeBoolean,
  nodeEvents,
  nodeNumber,
  nodeOptions,
  nodeRaw,
  nodeRecord,
  nodeString,
  nodeStringArray,
  nodeText,
  type NodeVisibleWhen,
  nodeVisibleWhen,
} from './ui-framework/node-properties.util';
export {
  isUnsupportedResolution,
  type NodeResolution,
  resolveRenderableNode,
  type UnsupportedResolution,
} from './ui-framework/node-resolution.util';
export { type UiNode, type UiNodeEvent } from './ui-framework/ui-node.interface';
export { applyUiPatch, type UiPatch, type UiPatchOperation, UiPatchOperations } from './ui-framework/ui-patch';
export { nodeResource, type UiResource } from './ui-framework/ui-resource';
export { UI_COMPONENT_EVENTS_WELL_KNOWN, UiComponentEvents } from './ui-components/component-events';
export {
  nodeHexColor,
  nodeLength,
  resolveLength,
  UI_COMPONENT_CELL,
  type UiLength,
} from './ui-framework/length';
export {
  intrinsicMainPx,
  layoutStackChildren,
  type UiComponentBox,
  type UiComponentStackChild,
  type UiIntrinsicMetrics,
} from './ui-framework/layout';
export {
  barEnd,
  barFillStyle,
  barHasMarker,
  barMarkerDiameterPx,
  barMarkerLeftPx,
  barMarkerStrokePx,
  barStart,
  progressFillStyle,
  sliderDirection,
  sliderIsVertical,
  sliderLevel,
  sliderLevelColor,
  sliderLevelFromPointer,
  sliderThumbDiameterPx,
  sliderThumbOffsetPx,
  sliderThumbStrokePx,
} from './ui-components/bar';
export {
  artworkCrossfades,
  artworkFilter,
  buttonArtworkTransform,
  buttonBackground,
  buttonBorder,
  widgetTileBorder,
  buttonFit,
  buttonOpacity,
  buttonZoom,
  chartColor,
  chartPlotTop,
  chartPoints,
  clampUnit,
  nodeAlign,
  nodeDirection,
  nodeGapPx,
  nodeIsHorizontal,
  nodeJustify,
  nodePaddingPx,
  nodeThicknessPx,
  stackBackground,
  showsSeconds,
  textAlign,
  textDigits,
  textFillColor,
  textFontWeight,
  textMaxLines,
  textRoleColor,
  textWraps,
} from './ui-components/style';
export { reloadFailedImages } from './ui-components/image-recovery';
export {
  browserLockEnvironment,
  type CrossTabLockEnvironment,
  type CrossTabLockStorage,
  runExclusively,
  type WebLockManager,
} from './util/cross-tab-lock';
export {
  createHostUrlResolver,
  DEFAULT_WEB_CLIENT_TARGET,
  type HostEndpointCandidate,
  type HostEndpointEnvironment,
  type HostEndpointStrategy,
  type HostUrlResolver,
  type WebClientTarget,
  type WebClientTargetCapabilities,
} from './client-target/client-target';
export {
  containsTickingNode,
  findInteractiveNode,
  nodeClaimsValue,
  nodeClaimsGesture,
  treeClaimsGesture,
} from './ui-framework/node-gestures';
export { chartPaths, type UiChartPaths } from './ui-components/chart';
export {
  dialAngles,
  dialHands,
  dialMetrics,
  dialTicks,
  type UiDialLine,
  type UiDialMetrics,
  type UiDialTick,
} from './macrodeck-components/dial';
export {
  UI_COMPONENT_BORDER_STYLES_WELL_KNOWN,
  UI_COMPONENT_BUTTON_CORNERS_WELL_KNOWN,
  UI_COMPONENT_IMAGE_TRANSITIONS_WELL_KNOWN,
  UI_COMPONENTS_WELL_KNOWN,
  UiComponentAlignments,
  UiComponentBorderStyles,
  UiComponentButtonCorners,
  UiComponentDirections,
  UiComponentImageFits,
  UiComponentImageTransitions,
  UiComponentJustify,
  UiComponents,
  UiComponentTextRoles,
  UiComponentTextWeights,
} from './ui-components/ui-component-types';
export {
  UI_MACRODECK_COMPONENTS_WELL_KNOWN,
  UiMacroDeckComponents,
} from './macrodeck-components/macrodeck-component-types';
export {
  formatDuration,
  formatProgressRun,
  nodeProgressRef,
  resolveProgressFraction,
  resolveProgressMs,
  UI_PROGRESS_FORMATS_WELL_KNOWN,
  type UiProgressRef,
  UiProgressFormats,
} from './macrodeck-components/progress';
export { UI_COMPONENT_PROPERTIES_WELL_KNOWN, UiComponentProperties } from './ui-components/component-properties';
export {
  formatDate,
  formatTimeRun,
  formatZoneName,
  isSupportedZone,
  nodeTimeRef,
  UI_TIME_FORMATS_WELL_KNOWN,
  type UiTimeRef,
  type UiTimeRun,
  UiTimeFormats,
  zonedClockParts,
} from './macrodeck-components/time';

// The host wire protocol
export {
  type ActionButtonStateAppearance,
  type ActionButtonStateOption,
  type ActionDefinition,
  type ActionExecutionResult,
  type ActionExecutionStatus,
  type ActionExecutionStatusEvent,
  type ActionOutcome,
  type ActionOutcomeStatus,
  type ActionParameterDef,
  type ActionParameterOption,
  ActionParameterType,
  type ActionProviderIconReference,
  type ExecuteActionButtonTriggerRequest,
  type ExecuteActionButtonTriggerResponse,
  type ExecuteActionRequest,
  type ExecuteActionResponse,
  type GetActionButtonStateOptionsRequest,
  type GetActionButtonStateOptionsResponse,
  type GetActionParameterOptionsRequest,
  type GetActionParameterOptionsResponse,
  type GetActionProviderIconRequest,
  type GetActionProviderIconResponse,
  type GetActionsRequest,
  type GetActionsResponse,
  isFailureExecutionStatus,
  type ParameterVisibility,
  type RunActionFlowRequest,
  type RunActionFlowResponse,
} from './protocol/messages/action';
export {
  type AuthScope,
  type AuthStatusResponse,
  type ChangePasswordRequest,
  type ChangeUsernameRequest,
  type LoginRequest,
  type RedeemDeviceEnrollmentRequest,
  type SetupRequest,
  type TokenResponse,
} from './protocol/messages/auth';
export {
  type AutomationCreatedEvent,
  type AutomationDeletedEvent,
  type AutomationUpdatedEvent,
  type CreateAutomationRequest,
  type CreateAutomationResponse,
  type DeleteAutomationResponse,
  type DuplicateAutomationResponse,
  type GetAutomationsResponse,
  type IpcAutomation,
  type UpdateAutomationRequest,
  type UpdateAutomationResponse,
} from './protocol/messages/automation';
export {
  type BackupComponentCatalogEntry,
  type BackupComponentGroupInfo,
  type BackupDependencyWarningDto,
  type BackupListChangedEvent,
  type BackupOperationKind,
  type BackupOperationProgressEvent,
  type BackupOperationStage,
  type BackupRecoveryKeyAvailability,
  type BackupRecoveryKeyResponse,
  type BackupRecoveryKeyStateChangedEvent,
  type BackupSummary,
  type BackupTrigger,
  type CancelRestoreRequest,
  type CancelRestoreResponse,
  type CommitRestoreRequest,
  type CommitRestoreResponse,
  type CreateBackupRequest,
  type CreateBackupResponse,
  type DeleteBackupResponse,
  type GetBackupRecoveryKeyStateResponse,
  type GetBackupSettingsResponse,
  type GetBackupsResponse,
  type GetBackupStatusResponse,
  type InspectBackupRequest,
  type InspectBackupResponse,
  type PendingRestoreSummary,
  type PrepareRestoreRequest,
  type PrepareRestoreResponse,
  type RestorePendingEvent,
  type RevealBackupRecoveryKeyRequest,
  type UpdateBackupSettingsRequest,
  type UpdateBackupSettingsResponse,
} from './protocol/messages/backup';
export {
  type AdvanceWebClientTargetProvisioningRequest,
  type WebClientTargetDto,
  type WebClientTargetProvisioningChoiceDto,
  type WebClientTargetProvisioningFieldDto,
  type WebClientTargetProvisioningLinkDto,
  type WebClientTargetProvisioningResultDto,
  type WebClientTargetProvisioningResultKind,
  type WebClientTargetProvisioningStepDto,
  type WebClientTargetProvisioningValueDto,
} from './protocol/messages/client-target';
export { type ApiError, type Result, type ResultResponse } from './protocol/messages/common';
export {
  type ConfigEntryDto,
  type ConfigFlowAuthorizedNotification,
  type ConfigFlowCopyValueDto,
  type ConfigFlowInstructionDto,
  type ConfigFlowLinkDto,
  type ConfigFlowOutcomeKind,
  type ConfigFlowStepDto,
  type DeleteConfigEntryResponse,
  type GetConfigEntriesResponse,
  type RenameConfigEntryResponse,
  type StartConfigFlowResponse,
  type SubmitConfigFlowStepRequest,
  type SubmitConfigFlowStepResponse,
} from './protocol/messages/config-flow';
export {
  type ConnectAccount,
  type ConnectConnectivity,
  type ConnectSessionChangedNotification,
  type ConnectSessionStatus,
  type ConnectSignInFailure,
  type GetConnectSessionResponse,
  type StartConnectSignInResponse,
} from './protocol/messages/connect';
export {
  type Device,
  type DeviceChangedEvent,
  type DeviceClientType,
  type DeviceCredential,
  type DeviceFormFactor,
  type DeviceLoginInfo,
  type DeviceRemovedEvent,
  type DeviceSessionRevokedEvent,
  type GetDevicesResponse,
  type LogoutDeviceResponse,
  type OpenProfileOnDeviceRequest,
  type OpenProfileOnDeviceResponse,
  type RemoveDeviceResponse,
  type RenameDeviceRequest,
  type RenameDeviceResponse,
  type SetDeviceStartupProfileRequest,
  type SetDeviceStartupProfileResponse,
} from './protocol/messages/device';
export {
  type ReportFolderChangedRequest,
  type ReportFolderChangedResponse,
  type TriggerEventRequest,
  type TriggerEventResponse,
} from './protocol/messages/event';
export {
  type FilesystemEntry,
  type GetFilesystemEntriesRequest,
  type GetFilesystemEntriesResponse,
} from './protocol/messages/filesystem';
export {
  type CreateFolderRequest,
  type CreateFolderResponse,
  type DeleteFolderFocusRuleRequest,
  type DeleteFolderFocusRuleResponse,
  type DeleteFolderRequest,
  type DeleteFolderResponse,
  type DuplicateFolderRequest,
  type DuplicateFolderResponse,
  type FolderCreatedEvent,
  type FolderDeletedEvent,
  type FolderFocusRule,
  type FolderFocusRuleChangedEvent,
  type FolderFocusRuleRemovedEvent,
  type FolderNavigationEvent,
  type FoldersReorderedEvent,
  type FolderUpdatedEvent,
  type GetFolderFocusRulesRequest,
  type GetFolderFocusRulesResponse,
  type GetFoldersRequest,
  type GetFoldersResponse,
  type IpcFolder,
  type IpcFolderPlacement,
  type MoveFolderRequest,
  type MoveFolderResponse,
  type SetFolderFocusRuleRequest,
  type SetFolderFocusRuleResponse,
  type UpdateFolderRequest,
  type UpdateFolderResponse,
} from './protocol/messages/folder';
export {
  type FolderViewCatalogChangedEvent,
  type GetFolderViewsRequest,
  type GetFolderViewsResponse,
  type IpcFolderView,
} from './protocol/messages/folder-view';
export { type GetHostSessionResponse } from './protocol/messages/host';
export {
  type CancelIconImportBatchResponse,
  type CreateIconPackRequest,
  type CreateIconPackResponse,
  type DeleteIconPackResponse,
  type DeleteIconResponse,
  type DeleteIconsRequest,
  type DeleteIconsResponse,
  type GetIconImportBatchResponse,
  type GetIconPacksRequest,
  type GetIconPacksResponse,
  type GetIconsRequest,
  type GetIconsResponse,
  type IconDeletedEvent,
  type IconImportBatchState,
  type IconImportProgressEvent,
  type IconPackCreatedEvent,
  type IconPackDeletedEvent,
  type IconPackUpdatedEvent,
  type IconProcessingState,
  type IconsAddedEvent,
  type IconUpdatedEvent,
  type ImportIconPacksResponse,
  type ImportIconsFromPathRequest,
  type ImportIconsResponse,
  type ImportSingleIconFromPathRequest,
  type ImportSingleIconResponse,
  type IpcIcon,
  type IpcIconImportBatch,
  type IpcIconPack,
  type UpdateIconPackRequest,
  type UpdateIconPackResponse,
  type UpdateIconRequest,
  type UpdateIconResponse,
} from './protocol/messages/icon';
export {
  type CapabilityAvailability,
  type GetIntegrationCapabilitiesResponse,
  type GetIntegrationIssuesResponse,
  type GetIntegrationsRequest,
  type GetIntegrationsResponse,
  type IntegrationIssuesChangedEvent,
  type IntegrationIssueSeverity,
  type IpcIntegration,
  type IpcIntegrationActionCapability,
  type IpcIntegrationIssue,
  type IpcIntegrationVariableCapability,
  type IpcProvidedCapability,
  type IssueResolutionFollowUp,
  type ResolveIntegrationIssueResponse,
  type SetIntegrationEnabledRequest,
  type SetIntegrationEnabledResponse,
} from './protocol/messages/integration';
export {
  type GetKeyRingProtectionResponse,
  type GetKeyRingStatusResponse,
  type KeyRingBackend,
  type KeyRingProtectionState,
  type UnlockKeyRingError,
  type UnlockKeyRingRequest,
  type UnlockKeyRingResponse,
} from './protocol/messages/key-ring';
export {
  type GetLocalizationResponse,
  type GetLocalizationSettingsResponse,
  type LocalizationCatalogChangedEvent,
  type LocalizationCultureChangedEvent,
  type UpdateLocalizationSettingsRequest,
  type UpdateLocalizationSettingsResponse,
} from './protocol/messages/localization';
export {
  type GetLogSourcesResponse,
  type GetLogsRequest,
  type GetLogsResponse,
  type LogEntriesAppendedNotification,
  type LogEntry,
  LogEntryLevel,
  LogEntrySource,
  type LogQuery,
  type LogSourceSummary,
} from './protocol/messages/logs';
export {
  type MigrationCredentialStatus,
  type MigrationImportResponse,
  type MigrationIntegrationDto,
  type MigrationPreviewResponse,
  type MigrationRequestBody,
  type MigrationSourceDto,
  type MigrationSourcesResponse,
  type MigrationSummary,
  type MigrationUnsupportedActionDto,
  type MigrationWarningDto,
} from './protocol/messages/migration';
export {
  type CompleteUiModalRequest,
  type CompleteUiModalResponse,
  type OpenModalUiSessionRequest,
  type OpenModalUiSessionResponse,
  type UiModalOpenedEvent,
} from './protocol/messages/modal';
export {
  type GetMusicPlayerInstancesResponse,
  type GetMusicPlayerStateResponse,
  type MusicPlayerInstanceDto,
  type MusicPlayerInstancesChangedNotification,
  type MusicPlayerStateChangedNotification,
  type MusicPlayerStatePayload,
} from './protocol/messages/music-player';
export {
  type GetUserNotificationsResponse,
  type UserNotification,
  type UserNotificationAction,
  type UserNotificationActionKind,
  type UserNotificationKind,
  type UserNotificationProgress,
  type UserNotificationsChangedEvent,
  type UserNotificationSeverity,
} from './protocol/messages/notification-center';
export {
  type CompatibilityFinding,
  type CompatibilityFindingSource,
  type CompatibilitySeverity,
  type GetPluginCompatibilityResponse,
  type PluginCompatibilityReport,
  type PluginCompatibilityState,
} from './protocol/messages/plugin-compatibility';
export {
  type GetInstalledPluginsResponse,
  type InstalledPlugin,
  type InstalledPluginVersion,
  PLUGIN_INSTALL_ERROR_ALREADY_INSTALLED,
  PLUGIN_WARNING_ARTIFACT_UNSIGNED,
  PLUGIN_WARNING_SIGNATURE_UNVERIFIED,
  type PluginArtifactInfo,
  type PluginInstallActionResponse,
  type PluginInstallWarning,
  type PluginInstallWarningSeverity,
  type PluginPublisherInfo,
  type PluginSignatureInfo,
  type PluginSignatureVerification,
  type PluginTrustCategory,
} from './protocol/messages/plugin-installation';
export {
  type ApprovePluginPairingRequestRequest,
  type GetPairedPluginsResponse,
  type GetPluginPairingRequestsResponse,
  type PairedPlugin,
  type PendingPluginPairingRequest,
  type PluginPairingActionResponse,
  type PluginPairingClientInfo,
} from './protocol/messages/plugin-pairing';
export {
  type GetPluginRuntimeResponse,
  type PluginRuntimeHealth,
  type PluginRuntimeInfo,
  type PluginRuntimeOperationResponse,
  type PluginRuntimeState,
  type PluginRuntimeStopReason,
} from './protocol/messages/plugin-runtime';
export {
  type CreatePluginTokenRequest,
  type CreatePluginTokenResponse,
  type DeletePluginTokenResponse,
  type GetPluginSessionsResponse,
  type GetPluginTokensResponse,
  type PluginAccessToken,
  type PluginRegistrationSummary,
  type PluginSessionInfo,
  type PluginSessionOrigin,
  type PluginSessionState,
  type RevokePluginTokenResponse,
  type TerminatePluginSessionResponse,
} from './protocol/messages/plugin-token';
export {
  type ArchiveIntegration,
  type ArchiveIntegrationAvailability,
  type ArchiveSummary,
  type ExportArchiveRequest,
  type ExportFolderRequest,
  type ExportProfileRequest,
  type ExportWidgetsRequest,
  type ImportFolderResponse,
  type ImportProfileResponse,
  type ImportWidgetsResponse,
  type InspectArchiveResponse,
} from './protocol/messages/portable';
export {
  type CreateProfileRequest,
  type CreateProfileResponse,
  type DeleteProfileRequest,
  type DeleteProfileResponse,
  type GetProfilesResponse,
  type IpcProfile,
  type IpcProfileLayout,
  type IpcProfileLayoutCompatibility,
  type IpcProfileLayoutCompatibilityStatus,
  type IpcProfileLayoutConstraint,
  type ProfileCreatedEvent,
  type ProfileDeletedEvent,
  type ProfileUpdatedEvent,
  type UpdateProfileRequest,
  type UpdateProfileResponse,
} from './protocol/messages/profile';
export {
  type CreateScriptRequest,
  type CreateScriptResponse,
  type DeleteScriptResponse,
  type DuplicateScriptResponse,
  type GetScriptsResponse,
  type GetScriptUsagesResponse,
  type IpcScript,
  type IpcScriptUsage,
  type RunScriptRequest,
  type RunScriptResponse,
  type ScriptCreatedEvent,
  type ScriptDeletedEvent,
  type ScriptUpdatedEvent,
  type UpdateScriptRequest,
  type UpdateScriptResponse,
} from './protocol/messages/script';
export {
  type CloneSecretResponse,
  type CreateSecretRequest,
  type CreateSecretResponse,
  type DeleteSecretResponse,
  type RevealSecretResponse,
  type SecretKind,
  type UpdateSecretRequest,
  type UpdateSecretResponse,
} from './protocol/messages/secret';
export {
  type ActiveTlsMode,
  type AdbDevice,
  type AdbDeviceState,
  type AdbStateChangedEvent,
  type AppearanceChangedEvent,
  type CompleteOnboardingRequest,
  type CompleteOnboardingResponse,
  type DeveloperSettingsChangedEvent,
  type DownloadAdbPlatformToolsResponse,
  type GetAdbSettingsResponse,
  type GetAppearanceSettingsResponse,
  type GetAutostartSettingsResponse,
  type GetDataDirectoryResponse,
  type GetDeveloperSettingsResponse,
  type GetLockScreenSettingsResponse,
  type GetLoggingSettingsResponse,
  type GetNetworkSettingsResponse,
  type GetOnboardingStateRequest,
  type GetOnboardingStateResponse,
  type OpenDataDirectoryResponse,
  type RestartAdbServerResponse,
  type RestartApplicationRequest,
  type RestartApplicationResponse,
  type ThemeMode,
  type TlsCertificateSource,
  type TlsMode,
  type UpdateAdbSettingsRequest,
  type UpdateAdbSettingsResponse,
  type UpdateAppearanceSettingsRequest,
  type UpdateAppearanceSettingsResponse,
  type UpdateAutostartSettingsRequest,
  type UpdateAutostartSettingsResponse,
  type UpdateDeveloperSettingsRequest,
  type UpdateDeveloperSettingsResponse,
  type UpdateLockScreenSettingsRequest,
  type UpdateLockScreenSettingsResponse,
  type UpdateLoggingSettingsRequest,
  type UpdateLoggingSettingsResponse,
  type UpdateNetworkSettingsRequest,
  type UpdateNetworkSettingsResponse,
  type UpdateNetworkTlsCertificateRequest,
} from './protocol/messages/settings';
export {
  type GetStoreCatalogResponse,
  type GetStoreExtensionResponse,
  type GetStoreOperationsResponse,
  type GetStoreStatusResponse,
  type GetStoreUpdatesResponse,
  type InstallStoreExtensionRequest,
  type RefreshStoreRegistryResponse,
  type StoreAvailableUpdateBody,
  type StoreCatalogChangedEvent,
  type StoreCatalogItemBody,
  type StoreCatalogSection,
  type StoreExtensionDetailBody,
  type StoreExtensionKind,
  type StoreExtensionTrust,
  type StoreInstallState,
  type StoreOperationActionResponse,
  type StoreOperationBody,
  type StoreOperationChangedEvent,
  type StoreOperationKind,
  type StoreOperationState,
  type StoreRegistryStatusBody,
  type StoreRegistryStatusChangedEvent,
  type StoreScreenshotBody,
  type StoreUpdatesChangedEvent,
  type StoreVersionHistoryBody,
  type UninstallStoreExtensionRequest,
  type UninstallStoreExtensionResponse,
} from './protocol/messages/store';
export {
  type ApplicationIdentityKind,
  type ConnectionEndpoint,
  type DeviceSetupCertificateAuthorityInfo,
  type FontFaceSlant,
  type GetAboutInfoResponse,
  type GetApplicationFocusCapabilityRequest,
  type GetApplicationFocusCapabilityResponse,
  type GetConnectionInfoResponse,
  type GetDeviceSetupResponse,
  type GetHostLockStateResponse,
  type GetRunningApplicationsRequest,
  type GetRunningApplicationsResponse,
  type GetSystemFontsRequest,
  type GetSystemFontsResponse,
  type HostLockStateChangedEvent,
  type RunningApplication,
  type SystemFontFace,
} from './protocol/messages/system';
export {
  type ComparisonExpressionPayload,
  type ComparisonLeafEvaluation,
  type ConditionExpressionPayload,
  type ConditionSidePayload,
  type EvaluateConditionRequest,
  type EvaluateConditionResponse,
  type EvaluateExpressionRequest,
  type EvaluateExpressionResponse,
  type LogicalExpressionPayload,
  type RenderTemplateRequest,
  type RenderTemplateResponse,
} from './protocol/messages/template';
export {
  type ListUiPreviewsRequest,
  type ListUiPreviewsResponse,
  type UiPreviewDiagnostic,
  type UiPreviewEntry,
} from './protocol/messages/ui-previews';
export {
  type OpenConfigUiSessionRequest,
  type OpenConfigUiSessionResponse,
  type OpenFolderUiSessionRequest,
  type OpenFolderUiSessionResponse,
  type OpenUiPreviewSessionRequest,
  type OpenUiPreviewSessionResponse,
  type OpenWidgetUiSessionRequest,
  type OpenWidgetUiSessionResponse,
  type UiAttachSessionRequest,
  type UiAttachSessionResponse,
  type UiSendEventRequest,
  type UiSendEventResponse,
  type UiSessionClosedEvent,
  type UiSessionInvalidatedEvent,
  type UiSessionPatchedEvent,
  type UiSessionTreeUpdatedEvent,
} from './protocol/messages/ui-session';
export {
  type BindCatalogVariableRequest,
  type BindCatalogVariableResponse,
  type CreateVariableRequest,
  type CreateVariableResponse,
  type DeleteVariableRequest,
  type DeleteVariableResponse,
  type DiscoverCatalogVariablesRequest,
  type DiscoverCatalogVariablesResponse,
  type VariableCatalogNode,
  type VariableCatalogProvider,
  type GetVariableCatalogProvidersRequest,
  type GetVariableCatalogProvidersResponse,
  type GetVariablesRequest,
  type GetVariablesResponse,
  type RenameCatalogVariableRequest,
  type RenameCatalogVariableResponse,
  type ResolveCatalogVariableRequest,
  type ResolveCatalogVariableResponse,
  type SanitizeVariableNameRequest,
  type SanitizeVariableNameResponse,
  type SetVariableValueRequest,
  type SetVariableValueResponse,
  type UnbindCatalogVariableRequest,
  type UnbindCatalogVariableResponse,
  type UpdateVariableRequest,
  type UpdateVariableResponse,
  type VariablesChangedEvent,
} from './protocol/messages/variable';
export {
  type GetServerTimeResponse,
  type GetVersionRequest,
  type GetVersionResponse,
} from './protocol/messages/version';
export {
  type GetWeatherInstancesResponse,
  type GetWeatherStateResponse,
  type WeatherForecastDayPayload,
  type WeatherInstanceDto,
  type WeatherInstancesChangedNotification,
  type WeatherStateChangedNotification,
  type WeatherStatePayload,
} from './protocol/messages/weather';
export {
  type CreateWidgetFromApplicationRequest,
  type CreateWidgetItem,
  type CreateWidgetRequest,
  type CreateWidgetResponse,
  type CreateWidgetsRequest,
  type CreateWidgetsResponse,
  type DeleteWidgetRequest,
  type DeleteWidgetResponse,
  type DeleteWidgetsRequest,
  type DeleteWidgetsResponse,
  type GetWidgetDataSchemasResponse,
  type IpcWidget,
  type IpcWidgetType,
  type LabelImagePreviewRequest,
  type LabelTextUpdatedEvent,
  type SetWidgetPinnedRequest,
  type SetWidgetPinnedResponse,
  type SetWidgetsPinnedRequest,
  type SetWidgetsPinnedResponse,
  type UpdateWidgetDataRequest,
  type UpdateWidgetDataResponse,
  type UpdateWidgetPositionsRequest,
  type UpdateWidgetPositionsResponse,
  type UpdateWidgetRequest,
  type UpdateWidgetResponse,
  type UpdateWidgetStateRequest,
  type UpdateWidgetStateResponse,
  type WidgetCreatedEvent,
  type WidgetDeletedEvent,
  type WidgetPositionsUpdatedEvent,
  type WidgetPositionUpdate,
  type WidgetsCreatedEvent,
  type WidgetsDeletedEvent,
  type WidgetStateChangedNotification,
  type WidgetStateUpdatedEvent,
  type WidgetsUpdatedEvent,
  type WidgetUpdatedEvent,
} from './protocol/messages/widget';
export {
  type GetWidgetTypesRequest,
  type GetWidgetTypesResponse,
  type WidgetTypeCatalogChangedEvent,
  type WidgetTypeDto,
} from './protocol/messages/widget-type';
export { TransportError } from './protocol/transport-error';
export { type RefreshOutcome, isUnreachable } from './protocol/refresh-outcome';
export { type WebSocketEnvelope, WebSocketTransport } from './protocol/websocket-transport';

// Localization primitives and the generated catalogues
export { bundledTranslator } from './localization/bundled-translator';
export { formatTemplate } from './localization/format-template.util';
export {
  AppStrings,
  AppStringsDefaults,
  type AppStringsKey,
  AppStringsScope,
} from './localization/generated/app-strings';
export {
  ClientAppStrings,
  ClientAppStringsDefaults,
  type ClientAppStringsKey,
  ClientAppStringsScope,
} from './localization/generated/client-app-strings';
export { Strings, StringsDefaults, type StringsKey, StringsScope } from './localization/generated/strings';
export {
  asLocalizedRef,
  type LocalizationTranslator,
  type LocalizedRef,
  type LocalizedText,
  type LocalizedTextRef,
  resolveLocalizedText,
} from './localization/localized-text';
export { pluralForm } from './localization/plural-form.util';

// Normalized client input
export { type ClientInputEvent } from './client-input/client-input-event';
export { type HardwareInputMap, type KeyBinding, type WheelBinding } from './client-input/hardware-input-map';
export {
  type HardwareInputContext,
  type HardwareInputSource,
  keyboardInputSource,
  wheelInputSource,
} from './client-input/hardware-input.source';

// Framework-free helpers
export { disablePageZoom } from './util/disable-page-zoom';
export { randomToken } from './util/random-token';
export { scrollActiveIntoView } from './util/scroll-active-into-view';
export { isSecureContext } from './util/secure-context';

// The framework-free widget renderer
export { hasIntlParts, setIntlSupportForTesting } from './ui-framework/intl-support';
export {
  supportsCustomProperties,
  setCustomPropertySupportForTesting,
} from './render/custom-properties';
export {
  renderUiNode,
  type UiNodeRenderHandle,
  type UiNodeRenderOptions,
  type UiRenderTimers,
} from './render/ui-node-renderer';
export { type UiRenderHost } from './render/ui-render-host';
export { PressFeedback, PRESS_FEEDBACK_MIN_VISIBLE_MS } from './render/press-feedback';
export { renderWidgetBorder, type WidgetBorderHandle } from './render/widget-border';
export {
  createUiComponentRegistry,
  DEFAULT_UI_COMPONENT_REGISTRY,
  MACRO_DECK_COMPONENTS,
  UI_CORE_COMPONENTS,
  type UiComponentContext,
  type UiComponentDefinition,
  type UiComponentRegistry,
} from './ui-framework/component-registry';
export {
  renderWidgetGrid,
  type TreeLookup,
  type WidgetGridHandle,
  type WidgetGridOptions,
} from './render/widget-grid';

// A small reactive value, and the REST half of the host protocol
export { store, type ReadableStore, type WritableStore } from './store/store';
export { HttpClient, type HttpClientOptions } from './transport/http-client';
export { websocketUrl } from './transport/websocket-url';
export { UiConnection, type UiConnectionOptions, type UiConnectionState } from './transport/ui-connection';

// The deck a runtime client shows, and where it currently is
export { DeckState, type DeckLocation } from './deck/deck-state';
export { UiSessionStore } from './deck/ui-session-store';
export { folderFromWire, foldersFromWire, widgetFromWire } from './protocol/folder-mapping';
export { rootNodeOf } from './ui-framework/ui-tree-document';
export { uiResourceUrl } from './ui-framework/ui-resource';
export {
  WIDGET_FIELD_BORDER_PX,
  WIDGET_FIELD_LINE_HEIGHT,
  WIDGET_FIELD_PADDING_EM,
} from './ui-framework/layout';
export {
  DEFAULT_CULTURE,
  LocalizationCatalog,
  type LocalizationCatalogSnapshot,
} from './localization/catalog';
