// Generated from the Macro Deck localization resources. Do not edit by hand.
// Regenerate: MACRODECK_UPDATE_GENERATED=1 dotnet test sdk/tests/MacroDeck.Localization.Tests.UnitTests

/// The scope every key below belongs to.
pub const SCOPE: &str = "macrodeck.app";

/// The culture the compiled-in text is written in, and the last resort of the fallback chain.
pub const DEFAULT_CULTURE: &str = "en";

/// Every key this module carries.
#[rustfmt::skip]
#[allow(dead_code)]
pub mod keys {
    pub const ERRORS_COULD_NOT_BE_MOVED_TITLE: &str = "Bootstrapper.Errors.CouldNotBeMovedTitle";
    pub const ERRORS_COULD_NOT_RESTART_TITLE: &str = "Bootstrapper.Errors.CouldNotRestartTitle";
    pub const ERRORS_COULD_NOT_START_TITLE: &str = "Bootstrapper.Errors.CouldNotStartTitle";
    pub const ERRORS_HOST_BINARY_MISSING: &str = "Bootstrapper.Errors.HostBinaryMissing";
    pub const ERRORS_HOST_DID_NOT_START: &str = "Bootstrapper.Errors.HostDidNotStart";
    pub const ERRORS_HOST_DID_NOT_START_WITH_LOG: &str = "Bootstrapper.Errors.HostDidNotStartWithLog";
    pub const ERRORS_HOST_PORT_NOT_RESOLVED: &str = "Bootstrapper.Errors.HostPortNotResolved";
    pub const ERRORS_HOST_PROCESS_COULD_NOT_START: &str = "Bootstrapper.Errors.HostProcessCouldNotStart";
    pub const ERRORS_HOST_STOPPED_TITLE: &str = "Bootstrapper.Errors.HostStoppedTitle";
    pub const ERRORS_HOST_STOPPED_UNEXPECTEDLY: &str = "Bootstrapper.Errors.HostStoppedUnexpectedly";
    pub const ERRORS_INSTALL_LOCATION_UNKNOWN: &str = "Bootstrapper.Errors.InstallLocationUnknown";
    pub const ERRORS_MOVE_BUTTON_MOVE_TO_APPLICATIONS: &str = "Bootstrapper.Errors.MoveButtonMoveToApplications";
    pub const ERRORS_MOVE_COPY_FAILED: &str = "Bootstrapper.Errors.MoveCopyFailed";
    pub const ERRORS_MOVE_FAILED: &str = "Bootstrapper.Errors.MoveFailed";
    pub const ERRORS_MOVE_INSTALL_FAILED: &str = "Bootstrapper.Errors.MoveInstallFailed";
    pub const ERRORS_MOVE_NO_DESTINATION_FILE_NAME: &str = "Bootstrapper.Errors.MoveNoDestinationFileName";
    pub const ERRORS_MOVE_PROMPT: &str = "Bootstrapper.Errors.MovePrompt";
    pub const ERRORS_MOVE_PROMPT_REPLACES_EXISTING: &str = "Bootstrapper.Errors.MovePromptReplacesExisting";
    pub const ERRORS_MOVE_SET_ASIDE_FAILED: &str = "Bootstrapper.Errors.MoveSetAsideFailed";
    pub const ERRORS_MOVE_TO_APPLICATIONS_TITLE: &str = "Bootstrapper.Errors.MoveToApplicationsTitle";
    pub const ERRORS_NO_FREE_PORT: &str = "Bootstrapper.Errors.NoFreePort";
    pub const ERRORS_PORT_IN_USE: &str = "Bootstrapper.Errors.PortInUse";
    pub const ERRORS_PORT_IN_USE_WITH_LOG: &str = "Bootstrapper.Errors.PortInUseWithLog";
    pub const ERRORS_RESTART_FAILED: &str = "Bootstrapper.Errors.RestartFailed";
    pub const FILES_OPEN_DIALOG_FILTER: &str = "Bootstrapper.Files.OpenDialogFilter";
    pub const MENU_ABOUT: &str = "Bootstrapper.Menu.About";
    pub const MENU_ARCHIVE_FILTER: &str = "Bootstrapper.Menu.ArchiveFilter";
    pub const MENU_DISCORD: &str = "Bootstrapper.Menu.Discord";
    pub const MENU_EDIT: &str = "Bootstrapper.Menu.Edit";
    pub const MENU_FILE: &str = "Bootstrapper.Menu.File";
    pub const MENU_HELP: &str = "Bootstrapper.Menu.Help";
    pub const MENU_IMPORT: &str = "Bootstrapper.Menu.Import";
    pub const MENU_SETTINGS: &str = "Bootstrapper.Menu.Settings";
    pub const MENU_VIEW: &str = "Bootstrapper.Menu.View";
    pub const MENU_WINDOW: &str = "Bootstrapper.Menu.Window";
    pub const TRAY_QUIT: &str = "Bootstrapper.Tray.Quit";
    pub const TRAY_SHOW: &str = "Bootstrapper.Tray.Show";
    pub const UPDATE_ALL_FEEDS_FAILED: &str = "Bootstrapper.Update.AllFeedsFailed";
    pub const UPDATE_ALREADY_IN_PROGRESS: &str = "Bootstrapper.Update.AlreadyInProgress";
    pub const UPDATE_AVAILABLE_TITLE: &str = "Bootstrapper.Update.AvailableTitle";
    pub const UPDATE_BACKUP_FAILED: &str = "Bootstrapper.Update.BackupFailed";
    pub const UPDATE_BACKUP_GENERIC_FAILURE: &str = "Bootstrapper.Update.BackupGenericFailure";
    pub const UPDATE_BACKUP_HOST_UNREACHABLE: &str = "Bootstrapper.Update.BackupHostUnreachable";
    pub const UPDATE_BACKUP_UNCONFIRMED: &str = "Bootstrapper.Update.BackupUnconfirmed";
    pub const UPDATE_CHECK_FAILED: &str = "Bootstrapper.Update.CheckFailed";
    pub const UPDATE_CONFIRM_DOWNLOAD: &str = "Bootstrapper.Update.ConfirmDownload";
    pub const UPDATE_DOWNLOAD_AND_INSTALL: &str = "Bootstrapper.Update.DownloadAndInstall";
    pub const UPDATE_DOWNLOAD_FAILED: &str = "Bootstrapper.Update.DownloadFailed";
    pub const UPDATE_DOWNLOADED: &str = "Bootstrapper.Update.Downloaded";
    pub const UPDATE_EXTERNAL_AVAILABLE: &str = "Bootstrapper.Update.ExternalAvailable";
    pub const UPDATE_HOST_STOP_FAILED: &str = "Bootstrapper.Update.HostStopFailed";
    pub const UPDATE_INSTALL_FAILED: &str = "Bootstrapper.Update.InstallFailed";
    pub const UPDATE_LATER: &str = "Bootstrapper.Update.Later";
    pub const UPDATE_LINUX_NOT_SUPPORTED: &str = "Bootstrapper.Update.LinuxNotSupported";
    pub const UPDATE_NO_UPDATE_AVAILABLE: &str = "Bootstrapper.Update.NoUpdateAvailable";
    pub const UPDATE_NOT_AVAILABLE_IN_BUILD: &str = "Bootstrapper.Update.NotAvailableInBuild";
    pub const UPDATE_NOT_INSTALLED: &str = "Bootstrapper.Update.NotInstalled";
    pub const UPDATE_OPEN_DOWNLOAD_PAGE: &str = "Bootstrapper.Update.OpenDownloadPage";
    pub const UPDATE_PARTIAL_CHECK_FAILED: &str = "Bootstrapper.Update.PartialCheckFailed";
    pub const UPDATE_RESTART_NOW: &str = "Bootstrapper.Update.RestartNow";
}

/// Culture to its templates, sorted by key.
#[rustfmt::skip]
pub static CATALOG: &[(&str, &[(&str, &str)])] = &[
    ("cs", &[
        ("Bootstrapper.Errors.CouldNotBeMovedTitle", "Macro Deck se nepodařilo přesunout"),
        ("Bootstrapper.Errors.CouldNotRestartTitle", "Macro Deck se nepodařilo restartovat"),
        ("Bootstrapper.Errors.CouldNotStartTitle", "Macro Deck se nepodařilo spustit"),
        ("Bootstrapper.Errors.HostBinaryMissing", "Chybí spustitelný soubor hostitele Macro Deck:\n{paths}"),
        ("Bootstrapper.Errors.HostDidNotStart", "Proces hostitele Macro Deck se nespustil."),
        ("Bootstrapper.Errors.HostDidNotStartWithLog", "Proces hostitele Macro Deck se nespustil.\n\nVýstup hostitele:\n{log}"),
        ("Bootstrapper.Errors.HostPortNotResolved", "Port hostitele Macro Deck nebyl zjištěn, takže okno nelze vytvořit."),
        ("Bootstrapper.Errors.HostProcessCouldNotStart", "Proces hostitele Macro Deck se nepodařilo spustit:\n{error}"),
        ("Bootstrapper.Errors.HostStoppedTitle", "Hostitel Macro Deck se zastavil"),
        ("Bootstrapper.Errors.HostStoppedUnexpectedly", "Proces hostitele Macro Deck se neočekávaně zastavil (návratový kód {code}).\n\n{log}"),
        ("Bootstrapper.Errors.InstallLocationUnknown", "Umístění instalace Macro Deck se nepodařilo určit.\n\nPřetáhněte Macro Deck do složky Aplikace ve Finderu sami a poté jej odtud otevřete."),
        ("Bootstrapper.Errors.MoveButtonMoveToApplications", "Přesunout do Aplikací"),
        ("Bootstrapper.Errors.MoveCopyFailed", "Nepodařilo se zkopírovat Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveFailed", "{detail}\n\nPřetáhněte Macro Deck do složky Aplikace ve Finderu sami (nebo do složky Aplikace ve své domovské složce) a poté jej odtud otevřete."),
        ("Bootstrapper.Errors.MoveInstallFailed", "Nepodařilo se nainstalovat Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveNoDestinationFileName", "Cíl instalace Macro Deck nemá název souboru"),
        ("Bootstrapper.Errors.MovePrompt", "Macro Deck běží z diskového obrazu.\n\nPřesuňte jej do složky Aplikace, abyste jej nainstalovali. Macro Deck se poté bude otevírat odtud.\n\nSpouštění Macro Deck z diskového obrazu není podporováno: aplikace nemůže uložit své nastavení a nemůže instalovat aktualizace."),
        ("Bootstrapper.Errors.MovePromptReplacesExisting", "Macro Deck běží z diskového obrazu.\n\nPřesuňte jej do složky Aplikace, abyste jej nainstalovali. Macro Deck se poté bude otevírat odtud.\n\nSpouštění Macro Deck z diskového obrazu není podporováno: aplikace nemůže uložit své nastavení a nemůže instalovat aktualizace.\n\nTímto se nahradí stávající Macro Deck ve složce Aplikace."),
        ("Bootstrapper.Errors.MoveSetAsideFailed", "Nepodařilo se odložit stávající Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveToApplicationsTitle", "Přesunout Macro Deck do Aplikací"),
        ("Bootstrapper.Errors.NoFreePort", "Pro hostitele Macro Deck se nepodařilo přidělit žádný volný loopback port."),
        ("Bootstrapper.Errors.PortInUse", "Macro Deck se nepodařilo spustit, protože port {port} už používá jiná aplikace.\nZavřete aplikaci používající tento port (nebo stále běžící Macro Deck) a zkuste to znovu, nebo spusťte Macro Deck s proměnnou MACRO_DECK_PORT nastavenou na volný port, abyste to změnili zpět."),
        ("Bootstrapper.Errors.PortInUseWithLog", "Macro Deck se nepodařilo spustit, protože port {port} už používá jiná aplikace.\nZavřete aplikaci používající tento port (nebo stále běžící Macro Deck) a zkuste to znovu, nebo spusťte Macro Deck s proměnnou MACRO_DECK_PORT nastavenou na volný port, abyste to změnili zpět.\n\nVýstup hostitele:\n{log}"),
        ("Bootstrapper.Errors.RestartFailed", "Macro Deck se nepodařilo znovu spustit. Ukončete jej a spusťte znovu, aby se změna projevila."),
        ("Bootstrapper.Files.OpenDialogFilter", "Soubory"),
        ("Bootstrapper.Menu.About", "O aplikaci Macro Deck"),
        ("Bootstrapper.Menu.ArchiveFilter", "Archivy Macro Deck"),
        ("Bootstrapper.Menu.Discord", "Macro Deck na Discordu"),
        ("Bootstrapper.Menu.Edit", "Úpravy"),
        ("Bootstrapper.Menu.File", "Soubor"),
        ("Bootstrapper.Menu.Help", "Nápověda"),
        ("Bootstrapper.Menu.Import", "Importovat…"),
        ("Bootstrapper.Menu.Settings", "Nastavení…"),
        ("Bootstrapper.Menu.View", "Zobrazení"),
        ("Bootstrapper.Menu.Window", "Okno"),
        ("Bootstrapper.Tray.Quit", "Ukončit"),
        ("Bootstrapper.Tray.Show", "Zobrazit"),
        ("Bootstrapper.Update.AllFeedsFailed", "nepodařilo se zkontrolovat aktualizace v žádném zdroji ({reasons})"),
        ("Bootstrapper.Update.AlreadyInProgress", "Aktualizace se již instaluje."),
        ("Bootstrapper.Update.AvailableTitle", "K dispozici je aktualizace"),
        ("Bootstrapper.Update.BackupFailed", "Macro Deck se nepodařilo vytvořit zálohu před aktualizací, takže aktualizace nebyla nainstalována. {error}"),
        ("Bootstrapper.Update.BackupGenericFailure", "Záloha před aktualizací se nezdařila."),
        ("Bootstrapper.Update.BackupHostUnreachable", "Hostitel Macro Deck není dostupný, takže nebylo možné vytvořit zálohu."),
        ("Bootstrapper.Update.BackupUnconfirmed", "Macro Deck se nepodařilo potvrdit vytvoření zálohy."),
        ("Bootstrapper.Update.CheckFailed", "Nepodařilo se zkontrolovat aktualizace: {error}"),
        ("Bootstrapper.Update.ConfirmDownload", "Macro Deck {version} je k dispozici.\n\nStáhnout a nainstalovat nyní?"),
        ("Bootstrapper.Update.DownloadAndInstall", "Stáhnout a nainstalovat"),
        ("Bootstrapper.Update.DownloadFailed", "Nepodařilo se stáhnout aktualizaci: {error}"),
        ("Bootstrapper.Update.Downloaded", "Macro Deck {version} byl stažen.\n\nRestartujte Macro Deck, abyste nainstalovali aktualizaci."),
        ("Bootstrapper.Update.ExternalAvailable", "Je k dispozici Macro Deck {version}.\n\nStáhněte jej z webu Macro Deck a aktualizujte nainstalovaný AppImage, DEB nebo RPM. Macro Deck bude nadále běžet."),
        ("Bootstrapper.Update.HostStopFailed", "Hostitele Macro Deck se nepodařilo zastavit, takže aktualizace nebyla nainstalována. Macro Deck úplně ukončete a zkuste to znovu."),
        ("Bootstrapper.Update.InstallFailed", "Nepodařilo se nainstalovat aktualizaci: {error}"),
        ("Bootstrapper.Update.Later", "Později"),
        ("Bootstrapper.Update.LinuxNotSupported", "Macro Deck na Linuxu neinstaluje aktualizace sám. Stáhněte novou verzi z {downloadPageUrl} a aktualizujte svou instalaci AppImage, DEB nebo RPM."),
        ("Bootstrapper.Update.NoUpdateAvailable", "Není k dispozici žádná aktualizace."),
        ("Bootstrapper.Update.NotAvailableInBuild", "V tomto sestavení nejsou aktualizace k dispozici."),
        ("Bootstrapper.Update.NotInstalled", "Macro Deck běží z diskového obrazu nebo dočasné kopie, takže se nemůže aktualizovat sám. Přesuňte Macro Deck do složky Aplikace a otevřete jej odtud."),
        ("Bootstrapper.Update.OpenDownloadPage", "Otevřít stránku ke stažení"),
        ("Bootstrapper.Update.PartialCheckFailed.One", "Nepodařilo se zkontrolovat kanál aktualizací {names}."),
        ("Bootstrapper.Update.PartialCheckFailed.Other", "Nepodařilo se zkontrolovat kanály aktualizací {names}."),
        ("Bootstrapper.Update.RestartNow", "Restartovat nyní"),
    ]),
    ("de", &[
        ("Bootstrapper.Errors.CouldNotBeMovedTitle", "Macro Deck konnte nicht verschoben werden"),
        ("Bootstrapper.Errors.CouldNotRestartTitle", "Macro Deck konnte nicht neu gestartet werden"),
        ("Bootstrapper.Errors.CouldNotStartTitle", "Macro Deck konnte nicht gestartet werden"),
        ("Bootstrapper.Errors.HostBinaryMissing", "Die Host-Binärdatei von Macro Deck fehlt:\n{paths}"),
        ("Bootstrapper.Errors.HostDidNotStart", "Der Host-Prozess von Macro Deck wurde nicht gestartet."),
        ("Bootstrapper.Errors.HostDidNotStartWithLog", "Der Host-Prozess von Macro Deck wurde nicht gestartet.\n\nHost-Ausgabe:\n{log}"),
        ("Bootstrapper.Errors.HostPortNotResolved", "Der Host-Port von Macro Deck wurde nicht ermittelt, daher kann das Fenster nicht erstellt werden."),
        ("Bootstrapper.Errors.HostProcessCouldNotStart", "Der Host-Prozess von Macro Deck konnte nicht gestartet werden:\n{error}"),
        ("Bootstrapper.Errors.HostStoppedTitle", "Macro-Deck-Host beendet"),
        ("Bootstrapper.Errors.HostStoppedUnexpectedly", "Der Host-Prozess von Macro Deck wurde unerwartet beendet (Exitcode {code}).\n\n{log}"),
        ("Bootstrapper.Errors.InstallLocationUnknown", "Der Installationsort von Macro Deck konnte nicht ermittelt werden.\n\nZiehe Macro Deck selbst im Finder in den Programme-Ordner und öffne es von dort."),
        ("Bootstrapper.Errors.MoveButtonMoveToApplications", "In Programme verschieben"),
        ("Bootstrapper.Errors.MoveCopyFailed", "Macro Deck konnte nicht kopiert werden: {error}"),
        ("Bootstrapper.Errors.MoveFailed", "{detail}\n\nZiehe Macro Deck selbst im Finder in den Programme-Ordner (oder in den Programme-Ordner deines Benutzerordners) und öffne es von dort."),
        ("Bootstrapper.Errors.MoveInstallFailed", "Macro Deck konnte nicht installiert werden: {error}"),
        ("Bootstrapper.Errors.MoveNoDestinationFileName", "Das Installationsziel von Macro Deck hat keinen Dateinamen"),
        ("Bootstrapper.Errors.MovePrompt", "Macro Deck wird vom Disk-Image aus ausgeführt.\n\nVerschiebe es in den Programme-Ordner, um es zu installieren. Macro Deck wird danach von dort geöffnet.\n\nDer Betrieb von Macro Deck direkt vom Disk-Image aus wird nicht unterstützt: Die App kann ihre Einstellungen nicht speichern und keine Updates installieren."),
        ("Bootstrapper.Errors.MovePromptReplacesExisting", "Macro Deck wird vom Disk-Image aus ausgeführt.\n\nVerschiebe es in den Programme-Ordner, um es zu installieren. Macro Deck wird danach von dort geöffnet.\n\nDer Betrieb von Macro Deck direkt vom Disk-Image aus wird nicht unterstützt: Die App kann ihre Einstellungen nicht speichern und keine Updates installieren.\n\nDadurch wird das vorhandene Macro Deck im Programme-Ordner ersetzt."),
        ("Bootstrapper.Errors.MoveSetAsideFailed", "Das vorhandene Macro Deck konnte nicht beiseitegelegt werden: {error}"),
        ("Bootstrapper.Errors.MoveToApplicationsTitle", "Macro Deck in den Programme-Ordner verschieben"),
        ("Bootstrapper.Errors.NoFreePort", "Für den Macro-Deck-Host konnte kein freier Loopback-Port zugewiesen werden."),
        ("Bootstrapper.Errors.PortInUse", "Macro Deck konnte nicht gestartet werden, da Port {port} bereits von einer anderen Anwendung verwendet wird.\nBeende die Anwendung, die den Port belegt (oder ein noch laufendes Macro Deck), und versuche es erneut, oder starte Macro Deck mit MACRO_DECK_PORT auf einem freien Port."),
        ("Bootstrapper.Errors.PortInUseWithLog", "Macro Deck konnte nicht gestartet werden, da Port {port} bereits von einer anderen Anwendung verwendet wird.\nBeende die Anwendung, die den Port belegt (oder ein noch laufendes Macro Deck), und versuche es erneut, oder starte Macro Deck mit MACRO_DECK_PORT auf einem freien Port.\n\nHost-Ausgabe:\n{log}"),
        ("Bootstrapper.Errors.RestartFailed", "Macro Deck konnte sich nicht selbst neu starten. Beende die Anwendung und starte sie erneut, um die Änderung zu übernehmen."),
        ("Bootstrapper.Files.OpenDialogFilter", "Dateien"),
        ("Bootstrapper.Menu.About", "Über Macro Deck"),
        ("Bootstrapper.Menu.ArchiveFilter", "Macro-Deck-Archive"),
        ("Bootstrapper.Menu.Discord", "Macro Deck auf Discord"),
        ("Bootstrapper.Menu.Edit", "Bearbeiten"),
        ("Bootstrapper.Menu.File", "Datei"),
        ("Bootstrapper.Menu.Help", "Hilfe"),
        ("Bootstrapper.Menu.Import", "Importieren…"),
        ("Bootstrapper.Menu.Settings", "Einstellungen…"),
        ("Bootstrapper.Menu.View", "Ansicht"),
        ("Bootstrapper.Menu.Window", "Fenster"),
        ("Bootstrapper.Tray.Quit", "Beenden"),
        ("Bootstrapper.Tray.Show", "Anzeigen"),
        ("Bootstrapper.Update.AllFeedsFailed", "Updates konnten auf keinem Feed geprüft werden ({reasons})"),
        ("Bootstrapper.Update.AlreadyInProgress", "Es wird bereits ein Update installiert."),
        ("Bootstrapper.Update.AvailableTitle", "Update verfügbar"),
        ("Bootstrapper.Update.BackupFailed", "Macro Deck konnte vor dem Update keine Sicherung erstellen, daher wurde das Update nicht installiert. {error}"),
        ("Bootstrapper.Update.BackupGenericFailure", "Die Sicherung vor dem Update ist fehlgeschlagen."),
        ("Bootstrapper.Update.BackupHostUnreachable", "Der Macro-Deck-Host ist nicht erreichbar, daher konnte keine Sicherung erstellt werden."),
        ("Bootstrapper.Update.BackupUnconfirmed", "Macro Deck konnte nicht bestätigen, dass eine Sicherung erstellt wurde."),
        ("Bootstrapper.Update.CheckFailed", "Updates konnten nicht geprüft werden: {error}"),
        ("Bootstrapper.Update.ConfirmDownload", "Macro Deck {version} ist verfügbar.\n\nMöchtest du es jetzt herunterladen und installieren?"),
        ("Bootstrapper.Update.DownloadAndInstall", "Herunterladen & installieren"),
        ("Bootstrapper.Update.DownloadFailed", "Das Update konnte nicht heruntergeladen werden: {error}"),
        ("Bootstrapper.Update.Downloaded", "Macro Deck {version} wurde heruntergeladen.\n\nStarte Macro Deck neu, um das Update zu installieren."),
        ("Bootstrapper.Update.ExternalAvailable", "Macro Deck {version} ist verfügbar.\n\nLade es von der Macro-Deck-Website herunter und aktualisiere deine installierte AppImage-, DEB- oder RPM-Version. Macro Deck läuft währenddessen weiter."),
        ("Bootstrapper.Update.HostStopFailed", "Der Macro-Deck-Host konnte nicht beendet werden, daher wurde das Update nicht installiert. Beende Macro Deck vollständig und versuche es erneut."),
        ("Bootstrapper.Update.InstallFailed", "Das Update konnte nicht installiert werden: {error}"),
        ("Bootstrapper.Update.Later", "Später"),
        ("Bootstrapper.Update.LinuxNotSupported", "Macro Deck installiert Updates unter Linux nicht selbst. Lade die neue Version von {downloadPageUrl} herunter und aktualisiere deine AppImage-, DEB- oder RPM-Installation."),
        ("Bootstrapper.Update.NoUpdateAvailable", "Es ist kein Update verfügbar."),
        ("Bootstrapper.Update.NotAvailableInBuild", "In diesem Build sind keine Updates verfügbar."),
        ("Bootstrapper.Update.NotInstalled", "Macro Deck wird von einem Disk-Image oder einer temporären Kopie aus ausgeführt und kann sich daher nicht selbst aktualisieren. Verschiebe Macro Deck in den Programme-Ordner und öffne es von dort."),
        ("Bootstrapper.Update.OpenDownloadPage", "Downloadseite öffnen"),
        ("Bootstrapper.Update.PartialCheckFailed.One", "Der Update-Feed {names} konnte nicht geprüft werden."),
        ("Bootstrapper.Update.PartialCheckFailed.Other", "Die Update-Feeds {names} konnten nicht geprüft werden."),
        ("Bootstrapper.Update.RestartNow", "Jetzt neu starten"),
    ]),
    ("en", &[
        ("Bootstrapper.Errors.CouldNotBeMovedTitle", "Macro Deck could not be moved"),
        ("Bootstrapper.Errors.CouldNotRestartTitle", "Macro Deck could not restart"),
        ("Bootstrapper.Errors.CouldNotStartTitle", "Macro Deck could not start"),
        ("Bootstrapper.Errors.HostBinaryMissing", "The Macro Deck host binary is missing:\n{paths}"),
        ("Bootstrapper.Errors.HostDidNotStart", "The Macro Deck host process did not start."),
        ("Bootstrapper.Errors.HostDidNotStartWithLog", "The Macro Deck host process did not start.\n\nHost output:\n{log}"),
        ("Bootstrapper.Errors.HostPortNotResolved", "The Macro Deck host port is not resolved, so the window cannot be created."),
        ("Bootstrapper.Errors.HostProcessCouldNotStart", "The Macro Deck host process could not be started:\n{error}"),
        ("Bootstrapper.Errors.HostStoppedTitle", "Macro Deck host stopped"),
        ("Bootstrapper.Errors.HostStoppedUnexpectedly", "The Macro Deck host process stopped unexpectedly (exit code {code}).\n\n{log}"),
        ("Bootstrapper.Errors.InstallLocationUnknown", "Macro Deck's install location could not be determined.\n\nDrag Macro Deck to the Applications folder in Finder yourself, then open it from there."),
        ("Bootstrapper.Errors.MoveButtonMoveToApplications", "Move to Applications"),
        ("Bootstrapper.Errors.MoveCopyFailed", "Could not copy Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveFailed", "{detail}\n\nDrag Macro Deck to the Applications folder in Finder yourself (or to the Applications folder in your home folder), then open it from there."),
        ("Bootstrapper.Errors.MoveInstallFailed", "Could not install Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveNoDestinationFileName", "Macro Deck's install destination has no file name"),
        ("Bootstrapper.Errors.MovePrompt", "Macro Deck is running from the disk image.\n\nMove it to your Applications folder to install it. Macro Deck will then open from there.\n\nRunning Macro Deck from the disk image is not supported: the app cannot save its setup and cannot install updates."),
        ("Bootstrapper.Errors.MovePromptReplacesExisting", "Macro Deck is running from the disk image.\n\nMove it to your Applications folder to install it. Macro Deck will then open from there.\n\nRunning Macro Deck from the disk image is not supported: the app cannot save its setup and cannot install updates.\n\nThis will replace the existing Macro Deck in your Applications folder."),
        ("Bootstrapper.Errors.MoveSetAsideFailed", "Could not set aside the existing Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveToApplicationsTitle", "Move Macro Deck to Applications"),
        ("Bootstrapper.Errors.NoFreePort", "No free loopback port could be allocated for the Macro Deck host."),
        ("Bootstrapper.Errors.PortInUse", "Macro Deck could not start because port {port} is already in use by another application.\nClose the application using the port (or a still-running Macro Deck) and try again, or start Macro Deck with MACRO_DECK_PORT set to a free port to change it back."),
        ("Bootstrapper.Errors.PortInUseWithLog", "Macro Deck could not start because port {port} is already in use by another application.\nClose the application using the port (or a still-running Macro Deck) and try again, or start Macro Deck with MACRO_DECK_PORT set to a free port to change it back.\n\nHost output:\n{log}"),
        ("Bootstrapper.Errors.RestartFailed", "Macro Deck could not relaunch itself. Quit and start it again to apply the change."),
        ("Bootstrapper.Files.OpenDialogFilter", "Files"),
        ("Bootstrapper.Menu.About", "About Macro Deck"),
        ("Bootstrapper.Menu.ArchiveFilter", "Macro Deck archives"),
        ("Bootstrapper.Menu.Discord", "Macro Deck on Discord"),
        ("Bootstrapper.Menu.Edit", "Edit"),
        ("Bootstrapper.Menu.File", "File"),
        ("Bootstrapper.Menu.Help", "Help"),
        ("Bootstrapper.Menu.Import", "Import…"),
        ("Bootstrapper.Menu.Settings", "Settings…"),
        ("Bootstrapper.Menu.View", "View"),
        ("Bootstrapper.Menu.Window", "Window"),
        ("Bootstrapper.Tray.Quit", "Quit"),
        ("Bootstrapper.Tray.Show", "Show"),
        ("Bootstrapper.Update.AllFeedsFailed", "could not check for updates on any feed ({reasons})"),
        ("Bootstrapper.Update.AlreadyInProgress", "An update is already being installed."),
        ("Bootstrapper.Update.AvailableTitle", "Update available"),
        ("Bootstrapper.Update.BackupFailed", "Macro Deck could not create a backup before updating, so the update was not installed. {error}"),
        ("Bootstrapper.Update.BackupGenericFailure", "The backup before the update failed."),
        ("Bootstrapper.Update.BackupHostUnreachable", "The Macro Deck host is not reachable, so no backup could be created."),
        ("Bootstrapper.Update.BackupUnconfirmed", "Macro Deck could not confirm that a backup was created."),
        ("Bootstrapper.Update.CheckFailed", "Could not check for updates: {error}"),
        ("Bootstrapper.Update.ConfirmDownload", "Macro Deck {version} is available.\n\nDo you want to download and install it now?"),
        ("Bootstrapper.Update.DownloadAndInstall", "Download & install"),
        ("Bootstrapper.Update.DownloadFailed", "Could not download the update: {error}"),
        ("Bootstrapper.Update.Downloaded", "Macro Deck {version} has been downloaded.\n\nRestart Macro Deck to install the update."),
        ("Bootstrapper.Update.ExternalAvailable", "Macro Deck {version} is available.\n\nDownload it from the Macro Deck website and update the AppImage, DEB or RPM you installed. Macro Deck will keep running."),
        ("Bootstrapper.Update.HostStopFailed", "The Macro Deck host could not be stopped, so the update was not installed. Quit Macro Deck completely and try again."),
        ("Bootstrapper.Update.InstallFailed", "Could not install the update: {error}"),
        ("Bootstrapper.Update.Later", "Later"),
        ("Bootstrapper.Update.LinuxNotSupported", "Macro Deck does not install updates itself on Linux. Download the new version from {downloadPageUrl} and update your AppImage, DEB or RPM install."),
        ("Bootstrapper.Update.NoUpdateAvailable", "No update is available."),
        ("Bootstrapper.Update.NotAvailableInBuild", "Updates are not available in this build."),
        ("Bootstrapper.Update.NotInstalled", "Macro Deck is running from a disk image or a temporary copy, so it cannot update itself. Move Macro Deck to your Applications folder and open it from there."),
        ("Bootstrapper.Update.OpenDownloadPage", "Open download page"),
        ("Bootstrapper.Update.PartialCheckFailed.One", "Could not check the {names} update feed."),
        ("Bootstrapper.Update.PartialCheckFailed.Other", "Could not check the {names} update feeds."),
        ("Bootstrapper.Update.RestartNow", "Restart now"),
    ]),
    ("es", &[
        ("Bootstrapper.Errors.CouldNotBeMovedTitle", "No se pudo mover Macro Deck"),
        ("Bootstrapper.Errors.CouldNotRestartTitle", "No se pudo reiniciar Macro Deck"),
        ("Bootstrapper.Errors.CouldNotStartTitle", "No se pudo iniciar Macro Deck"),
        ("Bootstrapper.Errors.HostBinaryMissing", "Falta el binario del host de Macro Deck:\n{paths}"),
        ("Bootstrapper.Errors.HostDidNotStart", "El proceso del host de Macro Deck no se inició."),
        ("Bootstrapper.Errors.HostDidNotStartWithLog", "El proceso del host de Macro Deck no se inició.\n\nSalida del host:\n{log}"),
        ("Bootstrapper.Errors.HostPortNotResolved", "No se resolvió el puerto del host de Macro Deck, por lo que no se puede crear la ventana."),
        ("Bootstrapper.Errors.HostProcessCouldNotStart", "No se pudo iniciar el proceso del host de Macro Deck:\n{error}"),
        ("Bootstrapper.Errors.HostStoppedTitle", "El host de Macro Deck se detuvo"),
        ("Bootstrapper.Errors.HostStoppedUnexpectedly", "El proceso del host de Macro Deck se detuvo inesperadamente (código de salida {code}).\n\n{log}"),
        ("Bootstrapper.Errors.InstallLocationUnknown", "No se pudo determinar la ubicación de instalación de Macro Deck.\n\nArrastra tú mismo Macro Deck a la carpeta Aplicaciones en Finder y ábrelo desde allí."),
        ("Bootstrapper.Errors.MoveButtonMoveToApplications", "Mover a Aplicaciones"),
        ("Bootstrapper.Errors.MoveCopyFailed", "No se pudo copiar Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveFailed", "{detail}\n\nArrastra tú mismo Macro Deck a la carpeta Aplicaciones en Finder (o a la carpeta Aplicaciones de tu carpeta personal) y ábrelo desde allí."),
        ("Bootstrapper.Errors.MoveInstallFailed", "No se pudo instalar Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveNoDestinationFileName", "El destino de instalación de Macro Deck no tiene nombre de archivo"),
        ("Bootstrapper.Errors.MovePrompt", "Macro Deck se está ejecutando desde la imagen de disco.\n\nMuévelo a tu carpeta Aplicaciones para instalarlo. Macro Deck se abrirá entonces desde allí.\n\nEjecutar Macro Deck desde la imagen de disco no es compatible: la aplicación no puede guardar su configuración ni instalar actualizaciones."),
        ("Bootstrapper.Errors.MovePromptReplacesExisting", "Macro Deck se está ejecutando desde la imagen de disco.\n\nMuévelo a tu carpeta Aplicaciones para instalarlo. Macro Deck se abrirá entonces desde allí.\n\nEjecutar Macro Deck desde la imagen de disco no es compatible: la aplicación no puede guardar su configuración ni instalar actualizaciones.\n\nEsto reemplazará el Macro Deck existente en tu carpeta Aplicaciones."),
        ("Bootstrapper.Errors.MoveSetAsideFailed", "No se pudo apartar el Macro Deck existente: {error}"),
        ("Bootstrapper.Errors.MoveToApplicationsTitle", "Mover Macro Deck a Aplicaciones"),
        ("Bootstrapper.Errors.NoFreePort", "No se pudo asignar ningún puerto loopback libre para el host de Macro Deck."),
        ("Bootstrapper.Errors.PortInUse", "Macro Deck no pudo iniciarse porque el puerto {port} ya está en uso por otra aplicación.\nCierra la aplicación que usa el puerto (o un Macro Deck que aún esté en ejecución) e inténtalo de nuevo, o inicia Macro Deck con MACRO_DECK_PORT configurado en un puerto libre para revertirlo."),
        ("Bootstrapper.Errors.PortInUseWithLog", "Macro Deck no pudo iniciarse porque el puerto {port} ya está en uso por otra aplicación.\nCierra la aplicación que usa el puerto (o un Macro Deck que aún esté en ejecución) e inténtalo de nuevo, o inicia Macro Deck con MACRO_DECK_PORT configurado en un puerto libre para revertirlo.\n\nSalida del host:\n{log}"),
        ("Bootstrapper.Errors.RestartFailed", "Macro Deck no pudo reiniciarse a sí mismo. Ciérralo y vuelve a iniciarlo para aplicar el cambio."),
        ("Bootstrapper.Files.OpenDialogFilter", "Archivos"),
        ("Bootstrapper.Menu.About", "Acerca de Macro Deck"),
        ("Bootstrapper.Menu.ArchiveFilter", "Archivos de Macro Deck"),
        ("Bootstrapper.Menu.Discord", "Macro Deck en Discord"),
        ("Bootstrapper.Menu.Edit", "Editar"),
        ("Bootstrapper.Menu.File", "Archivo"),
        ("Bootstrapper.Menu.Help", "Ayuda"),
        ("Bootstrapper.Menu.Import", "Importar…"),
        ("Bootstrapper.Menu.Settings", "Configuración…"),
        ("Bootstrapper.Menu.View", "Ver"),
        ("Bootstrapper.Menu.Window", "Ventana"),
        ("Bootstrapper.Tray.Quit", "Salir"),
        ("Bootstrapper.Tray.Show", "Mostrar"),
        ("Bootstrapper.Update.AllFeedsFailed", "no se pudieron buscar actualizaciones en ningún feed ({reasons})"),
        ("Bootstrapper.Update.AlreadyInProgress", "Ya se está instalando una actualización."),
        ("Bootstrapper.Update.AvailableTitle", "Actualización disponible"),
        ("Bootstrapper.Update.BackupFailed", "Macro Deck no pudo crear una copia de seguridad antes de actualizar, por lo que la actualización no se instaló. {error}"),
        ("Bootstrapper.Update.BackupGenericFailure", "La copia de seguridad previa a la actualización falló."),
        ("Bootstrapper.Update.BackupHostUnreachable", "No se pudo contactar con el host de Macro Deck, por lo que no se pudo crear ninguna copia de seguridad."),
        ("Bootstrapper.Update.BackupUnconfirmed", "Macro Deck no pudo confirmar que se creara una copia de seguridad."),
        ("Bootstrapper.Update.CheckFailed", "No se pudieron buscar actualizaciones: {error}"),
        ("Bootstrapper.Update.ConfirmDownload", "Macro Deck {version} está disponible.\n\n¿Quieres descargarlo e instalarlo ahora?"),
        ("Bootstrapper.Update.DownloadAndInstall", "Descargar e instalar"),
        ("Bootstrapper.Update.DownloadFailed", "No se pudo descargar la actualización: {error}"),
        ("Bootstrapper.Update.Downloaded", "Se ha descargado Macro Deck {version}.\n\nReinicia Macro Deck para instalar la actualización."),
        ("Bootstrapper.Update.ExternalAvailable", "Macro Deck {version} está disponible.\n\nDescárgalo desde el sitio web de Macro Deck y actualiza el AppImage, DEB o RPM que instalaste. Macro Deck seguirá funcionando."),
        ("Bootstrapper.Update.HostStopFailed", "No se pudo detener el host de Macro Deck, por lo que la actualización no se instaló. Cierra Macro Deck por completo e inténtalo de nuevo."),
        ("Bootstrapper.Update.InstallFailed", "No se pudo instalar la actualización: {error}"),
        ("Bootstrapper.Update.Later", "Más tarde"),
        ("Bootstrapper.Update.LinuxNotSupported", "Macro Deck no instala actualizaciones por sí mismo en Linux. Descarga la nueva versión desde {downloadPageUrl} y actualiza tu instalación AppImage, DEB o RPM."),
        ("Bootstrapper.Update.NoUpdateAvailable", "No hay ninguna actualización disponible."),
        ("Bootstrapper.Update.NotAvailableInBuild", "Las actualizaciones no están disponibles en esta compilación."),
        ("Bootstrapper.Update.NotInstalled", "Macro Deck se está ejecutando desde una imagen de disco o una copia temporal, por lo que no puede actualizarse a sí mismo. Mueve Macro Deck a tu carpeta Aplicaciones y ábrelo desde allí."),
        ("Bootstrapper.Update.OpenDownloadPage", "Abrir página de descarga"),
        ("Bootstrapper.Update.PartialCheckFailed.One", "No se pudo comprobar el feed de actualizaciones de {names}."),
        ("Bootstrapper.Update.PartialCheckFailed.Other", "No se pudieron comprobar los feeds de actualizaciones de {names}."),
        ("Bootstrapper.Update.RestartNow", "Reiniciar ahora"),
    ]),
    ("fr", &[
        ("Bootstrapper.Errors.CouldNotBeMovedTitle", "Macro Deck n'a pas pu être déplacé"),
        ("Bootstrapper.Errors.CouldNotRestartTitle", "Macro Deck n'a pas pu redémarrer"),
        ("Bootstrapper.Errors.CouldNotStartTitle", "Macro Deck n'a pas pu démarrer"),
        ("Bootstrapper.Errors.HostBinaryMissing", "Le binaire hôte de Macro Deck est introuvable:\n{paths}"),
        ("Bootstrapper.Errors.HostDidNotStart", "Le processus hôte de Macro Deck n'a pas démarré."),
        ("Bootstrapper.Errors.HostDidNotStartWithLog", "Le processus hôte de Macro Deck n'a pas démarré.\n\nSortie de l'hôte:\n{log}"),
        ("Bootstrapper.Errors.HostPortNotResolved", "Le port hôte de Macro Deck n'est pas résolu, la fenêtre ne peut donc pas être créée."),
        ("Bootstrapper.Errors.HostProcessCouldNotStart", "Le processus hôte de Macro Deck n'a pas pu démarrer:\n{error}"),
        ("Bootstrapper.Errors.HostStoppedTitle", "L'hôte Macro Deck s'est arrêté"),
        ("Bootstrapper.Errors.HostStoppedUnexpectedly", "Le processus hôte de Macro Deck s'est arrêté de manière inattendue (code de sortie {code}).\n\n{log}"),
        ("Bootstrapper.Errors.InstallLocationUnknown", "L'emplacement d'installation de Macro Deck n'a pas pu être déterminé.\n\nGlisse Macro Deck toi-même dans le dossier Applications dans le Finder, puis ouvre-le depuis là."),
        ("Bootstrapper.Errors.MoveButtonMoveToApplications", "Déplacer vers Applications"),
        ("Bootstrapper.Errors.MoveCopyFailed", "Impossible de copier Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveFailed", "{detail}\n\nGlisse Macro Deck toi-même dans le dossier Applications dans le Finder (ou dans le dossier Applications de ton dossier personnel), puis ouvre-le depuis là."),
        ("Bootstrapper.Errors.MoveInstallFailed", "Impossible d'installer Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveNoDestinationFileName", "La destination d'installation de Macro Deck n'a pas de nom de fichier"),
        ("Bootstrapper.Errors.MovePrompt", "Macro Deck s'exécute depuis l'image disque.\n\nDéplace-le vers ton dossier Applications pour l'installer. Macro Deck s'ouvrira ensuite depuis là.\n\nExécuter Macro Deck depuis l'image disque n'est pas pris en charge: l'application ne peut pas enregistrer sa configuration ni installer de mises à jour."),
        ("Bootstrapper.Errors.MovePromptReplacesExisting", "Macro Deck s'exécute depuis l'image disque.\n\nDéplace-le vers ton dossier Applications pour l'installer. Macro Deck s'ouvrira ensuite depuis là.\n\nExécuter Macro Deck depuis l'image disque n'est pas pris en charge: l'application ne peut pas enregistrer sa configuration ni installer de mises à jour.\n\nCeci remplacera le Macro Deck existant dans ton dossier Applications."),
        ("Bootstrapper.Errors.MoveSetAsideFailed", "Impossible de mettre de côté le Macro Deck existant: {error}"),
        ("Bootstrapper.Errors.MoveToApplicationsTitle", "Déplacer Macro Deck vers Applications"),
        ("Bootstrapper.Errors.NoFreePort", "Aucun port de bouclage libre n'a pu être alloué pour l'hôte de Macro Deck."),
        ("Bootstrapper.Errors.PortInUse", "Macro Deck n'a pas pu démarrer car le port {port} est déjà utilisé par une autre application.\nFerme l'application utilisant ce port (ou un Macro Deck encore en cours d'exécution) et réessaie, ou démarre Macro Deck avec MACRO_DECK_PORT défini sur un port libre pour revenir en arrière."),
        ("Bootstrapper.Errors.PortInUseWithLog", "Macro Deck n'a pas pu démarrer car le port {port} est déjà utilisé par une autre application.\nFerme l'application utilisant ce port (ou un Macro Deck encore en cours d'exécution) et réessaie, ou démarre Macro Deck avec MACRO_DECK_PORT défini sur un port libre pour revenir en arrière.\n\nSortie de l'hôte:\n{log}"),
        ("Bootstrapper.Errors.RestartFailed", "Macro Deck n'a pas pu se relancer lui-même. Quitte-le et redémarre-le pour appliquer le changement."),
        ("Bootstrapper.Files.OpenDialogFilter", "Fichiers"),
        ("Bootstrapper.Menu.About", "À propos de Macro Deck"),
        ("Bootstrapper.Menu.ArchiveFilter", "Archives Macro Deck"),
        ("Bootstrapper.Menu.Discord", "Macro Deck sur Discord"),
        ("Bootstrapper.Menu.Edit", "Édition"),
        ("Bootstrapper.Menu.File", "Fichier"),
        ("Bootstrapper.Menu.Help", "Aide"),
        ("Bootstrapper.Menu.Import", "Importer…"),
        ("Bootstrapper.Menu.Settings", "Paramètres…"),
        ("Bootstrapper.Menu.View", "Affichage"),
        ("Bootstrapper.Menu.Window", "Fenêtre"),
        ("Bootstrapper.Tray.Quit", "Quitter"),
        ("Bootstrapper.Tray.Show", "Afficher"),
        ("Bootstrapper.Update.AllFeedsFailed", "impossible de vérifier les mises à jour sur aucun flux ({reasons})"),
        ("Bootstrapper.Update.AlreadyInProgress", "Une mise à jour est déjà en cours d'installation."),
        ("Bootstrapper.Update.AvailableTitle", "Mise à jour disponible"),
        ("Bootstrapper.Update.BackupFailed", "Macro Deck n'a pas pu créer de sauvegarde avant la mise à jour, celle-ci n'a donc pas été installée. {error}"),
        ("Bootstrapper.Update.BackupGenericFailure", "La sauvegarde avant la mise à jour a échoué."),
        ("Bootstrapper.Update.BackupHostUnreachable", "L'hôte Macro Deck n'est pas joignable, aucune sauvegarde n'a donc pu être créée."),
        ("Bootstrapper.Update.BackupUnconfirmed", "Macro Deck n'a pas pu confirmer qu'une sauvegarde avait été créée."),
        ("Bootstrapper.Update.CheckFailed", "Impossible de vérifier les mises à jour: {error}"),
        ("Bootstrapper.Update.ConfirmDownload", "Macro Deck {version} est disponible.\n\nVeux-tu le télécharger et l'installer maintenant ?"),
        ("Bootstrapper.Update.DownloadAndInstall", "Télécharger et installer"),
        ("Bootstrapper.Update.DownloadFailed", "Impossible de télécharger la mise à jour: {error}"),
        ("Bootstrapper.Update.Downloaded", "Macro Deck {version} a été téléchargé.\n\nRedémarre Macro Deck pour installer la mise à jour."),
        ("Bootstrapper.Update.ExternalAvailable", "Macro Deck {version} est disponible.\n\nTélécharge-le depuis le site web de Macro Deck et mets à jour l'AppImage, le DEB ou le RPM que tu as installé. Macro Deck continuera de fonctionner."),
        ("Bootstrapper.Update.HostStopFailed", "L'hôte Macro Deck n'a pas pu être arrêté, la mise à jour n'a donc pas été installée. Quitte complètement Macro Deck et réessaie."),
        ("Bootstrapper.Update.InstallFailed", "Impossible d'installer la mise à jour: {error}"),
        ("Bootstrapper.Update.Later", "Plus tard"),
        ("Bootstrapper.Update.LinuxNotSupported", "Macro Deck n'installe pas lui-même les mises à jour sous Linux. Télécharge la nouvelle version depuis {downloadPageUrl} et mets à jour ton installation AppImage, DEB ou RPM."),
        ("Bootstrapper.Update.NoUpdateAvailable", "Aucune mise à jour disponible."),
        ("Bootstrapper.Update.NotAvailableInBuild", "Les mises à jour ne sont pas disponibles dans cette version."),
        ("Bootstrapper.Update.NotInstalled", "Macro Deck s'exécute depuis une image disque ou une copie temporaire, il ne peut donc pas se mettre à jour lui-même. Déplace Macro Deck vers ton dossier Applications et ouvre-le depuis là."),
        ("Bootstrapper.Update.OpenDownloadPage", "Ouvrir la page de téléchargement"),
        ("Bootstrapper.Update.PartialCheckFailed.One", "Impossible de vérifier le flux de mise à jour de {names}."),
        ("Bootstrapper.Update.PartialCheckFailed.Other", "Impossible de vérifier les flux de mise à jour de {names}."),
        ("Bootstrapper.Update.RestartNow", "Redémarrer maintenant"),
    ]),
    ("it", &[
        ("Bootstrapper.Errors.CouldNotBeMovedTitle", "Impossibile spostare Macro Deck"),
        ("Bootstrapper.Errors.CouldNotRestartTitle", "Impossibile riavviare Macro Deck"),
        ("Bootstrapper.Errors.CouldNotStartTitle", "Impossibile avviare Macro Deck"),
        ("Bootstrapper.Errors.HostBinaryMissing", "Il file eseguibile host di Macro Deck è mancante:\n{paths}"),
        ("Bootstrapper.Errors.HostDidNotStart", "Il processo host di Macro Deck non è partito."),
        ("Bootstrapper.Errors.HostDidNotStartWithLog", "Il processo host di Macro Deck non è partito.\n\nOutput dell'host:\n{log}"),
        ("Bootstrapper.Errors.HostPortNotResolved", "La porta host di Macro Deck non è stata risolta, quindi non è possibile creare la finestra."),
        ("Bootstrapper.Errors.HostProcessCouldNotStart", "Impossibile avviare il processo host di Macro Deck:\n{error}"),
        ("Bootstrapper.Errors.HostStoppedTitle", "L'host di Macro Deck si è arrestato"),
        ("Bootstrapper.Errors.HostStoppedUnexpectedly", "Il processo host di Macro Deck si è arrestato inaspettatamente (codice di uscita {code}).\n\n{log}"),
        ("Bootstrapper.Errors.InstallLocationUnknown", "Non è stato possibile determinare la posizione di installazione di Macro Deck.\n\nTrascina tu stesso Macro Deck nella cartella Applicazioni in Finder, quindi aprilo da lì."),
        ("Bootstrapper.Errors.MoveButtonMoveToApplications", "Sposta in Applicazioni"),
        ("Bootstrapper.Errors.MoveCopyFailed", "Impossibile copiare Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveFailed", "{detail}\n\nTrascina tu stesso Macro Deck nella cartella Applicazioni in Finder (oppure nella cartella Applicazioni della tua cartella home), quindi aprilo da lì."),
        ("Bootstrapper.Errors.MoveInstallFailed", "Impossibile installare Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveNoDestinationFileName", "La destinazione di installazione di Macro Deck non ha un nome file"),
        ("Bootstrapper.Errors.MovePrompt", "Macro Deck è in esecuzione dall'immagine disco.\n\nSpostalo nella cartella Applicazioni per installarlo. Macro Deck si aprirà quindi da lì.\n\nL'esecuzione di Macro Deck dall'immagine disco non è supportata: l'app non può salvare la propria configurazione né installare aggiornamenti."),
        ("Bootstrapper.Errors.MovePromptReplacesExisting", "Macro Deck è in esecuzione dall'immagine disco.\n\nSpostalo nella cartella Applicazioni per installarlo. Macro Deck si aprirà quindi da lì.\n\nL'esecuzione di Macro Deck dall'immagine disco non è supportata: l'app non può salvare la propria configurazione né installare aggiornamenti.\n\nQuesto sostituirà il Macro Deck già presente nella cartella Applicazioni."),
        ("Bootstrapper.Errors.MoveSetAsideFailed", "Impossibile accantonare il Macro Deck esistente: {error}"),
        ("Bootstrapper.Errors.MoveToApplicationsTitle", "Sposta Macro Deck in Applicazioni"),
        ("Bootstrapper.Errors.NoFreePort", "Non è stato possibile allocare una porta loopback libera per l'host di Macro Deck."),
        ("Bootstrapper.Errors.PortInUse", "Macro Deck non è riuscito ad avviarsi perché la porta {port} è già in uso da un'altra applicazione.\nChiudi l'applicazione che utilizza la porta (o un Macro Deck ancora in esecuzione) e riprova, oppure avvia Macro Deck con MACRO_DECK_PORT impostata su una porta libera per ripristinarla."),
        ("Bootstrapper.Errors.PortInUseWithLog", "Macro Deck non è riuscito ad avviarsi perché la porta {port} è già in uso da un'altra applicazione.\nChiudi l'applicazione che utilizza la porta (o un Macro Deck ancora in esecuzione) e riprova, oppure avvia Macro Deck con MACRO_DECK_PORT impostata su una porta libera per ripristinarla.\n\nOutput dell'host:\n{log}"),
        ("Bootstrapper.Errors.RestartFailed", "Macro Deck non è riuscito a riavviarsi da solo. Chiudilo e avvialo di nuovo per applicare la modifica."),
        ("Bootstrapper.Files.OpenDialogFilter", "File"),
        ("Bootstrapper.Menu.About", "Informazioni su Macro Deck"),
        ("Bootstrapper.Menu.ArchiveFilter", "Archivi Macro Deck"),
        ("Bootstrapper.Menu.Discord", "Macro Deck su Discord"),
        ("Bootstrapper.Menu.Edit", "Modifica"),
        ("Bootstrapper.Menu.File", "File"),
        ("Bootstrapper.Menu.Help", "Aiuto"),
        ("Bootstrapper.Menu.Import", "Importa…"),
        ("Bootstrapper.Menu.Settings", "Impostazioni…"),
        ("Bootstrapper.Menu.View", "Vista"),
        ("Bootstrapper.Menu.Window", "Finestra"),
        ("Bootstrapper.Tray.Quit", "Esci"),
        ("Bootstrapper.Tray.Show", "Mostra"),
        ("Bootstrapper.Update.AllFeedsFailed", "impossibile controllare gli aggiornamenti su nessun feed ({reasons})"),
        ("Bootstrapper.Update.AlreadyInProgress", "È già in corso l'installazione di un aggiornamento."),
        ("Bootstrapper.Update.AvailableTitle", "Aggiornamento disponibile"),
        ("Bootstrapper.Update.BackupFailed", "Macro Deck non è riuscito a creare un backup prima dell'aggiornamento, quindi l'aggiornamento non è stato installato. {error}"),
        ("Bootstrapper.Update.BackupGenericFailure", "Il backup precedente all'aggiornamento non è riuscito."),
        ("Bootstrapper.Update.BackupHostUnreachable", "L'host di Macro Deck non è raggiungibile, quindi non è stato possibile creare alcun backup."),
        ("Bootstrapper.Update.BackupUnconfirmed", "Macro Deck non è riuscito a confermare la creazione di un backup."),
        ("Bootstrapper.Update.CheckFailed", "Impossibile controllare gli aggiornamenti: {error}"),
        ("Bootstrapper.Update.ConfirmDownload", "Macro Deck {version} è disponibile.\n\nVuoi scaricarlo e installarlo ora?"),
        ("Bootstrapper.Update.DownloadAndInstall", "Scarica e installa"),
        ("Bootstrapper.Update.DownloadFailed", "Impossibile scaricare l'aggiornamento: {error}"),
        ("Bootstrapper.Update.Downloaded", "Macro Deck {version} è stato scaricato.\n\nRiavvia Macro Deck per installare l'aggiornamento."),
        ("Bootstrapper.Update.ExternalAvailable", "Macro Deck {version} è disponibile.\n\nScaricalo dal sito di Macro Deck e aggiorna l'AppImage, il DEB o l'RPM che hai installato. Macro Deck continuerà a funzionare."),
        ("Bootstrapper.Update.HostStopFailed", "Non è stato possibile arrestare l'host di Macro Deck, quindi l'aggiornamento non è stato installato. Chiudi completamente Macro Deck e riprova."),
        ("Bootstrapper.Update.InstallFailed", "Impossibile installare l'aggiornamento: {error}"),
        ("Bootstrapper.Update.Later", "Più tardi"),
        ("Bootstrapper.Update.LinuxNotSupported", "Su Linux Macro Deck non installa autonomamente gli aggiornamenti. Scarica la nuova versione da {downloadPageUrl} e aggiorna la tua installazione AppImage, DEB o RPM."),
        ("Bootstrapper.Update.NoUpdateAvailable", "Nessun aggiornamento disponibile."),
        ("Bootstrapper.Update.NotAvailableInBuild", "Gli aggiornamenti non sono disponibili in questa build."),
        ("Bootstrapper.Update.NotInstalled", "Macro Deck è in esecuzione da un'immagine disco o da una copia temporanea, quindi non può aggiornarsi da solo. Sposta Macro Deck nella cartella Applicazioni e aprilo da lì."),
        ("Bootstrapper.Update.OpenDownloadPage", "Apri pagina di download"),
        ("Bootstrapper.Update.PartialCheckFailed.One", "Impossibile controllare il feed di aggiornamento di {names}."),
        ("Bootstrapper.Update.PartialCheckFailed.Other", "Impossibile controllare i feed di aggiornamento di {names}."),
        ("Bootstrapper.Update.RestartNow", "Riavvia ora"),
    ]),
    ("pl", &[
        ("Bootstrapper.Errors.CouldNotBeMovedTitle", "Nie udało się przenieść Macro Deck"),
        ("Bootstrapper.Errors.CouldNotRestartTitle", "Nie udało się ponownie uruchomić Macro Deck"),
        ("Bootstrapper.Errors.CouldNotStartTitle", "Nie udało się uruchomić Macro Deck"),
        ("Bootstrapper.Errors.HostBinaryMissing", "Brak pliku wykonywalnego hosta Macro Deck:\n{paths}"),
        ("Bootstrapper.Errors.HostDidNotStart", "Proces hosta Macro Deck nie uruchomił się."),
        ("Bootstrapper.Errors.HostDidNotStartWithLog", "Proces hosta Macro Deck nie uruchomił się.\n\nDane wyjściowe hosta:\n{log}"),
        ("Bootstrapper.Errors.HostPortNotResolved", "Nie ustalono portu hosta Macro Deck, więc nie można utworzyć okna."),
        ("Bootstrapper.Errors.HostProcessCouldNotStart", "Nie udało się uruchomić procesu hosta Macro Deck:\n{error}"),
        ("Bootstrapper.Errors.HostStoppedTitle", "Host Macro Deck zatrzymany"),
        ("Bootstrapper.Errors.HostStoppedUnexpectedly", "Proces hosta Macro Deck zatrzymał się nieoczekiwanie (kod zakończenia {code}).\n\n{log}"),
        ("Bootstrapper.Errors.InstallLocationUnknown", "Nie udało się ustalić lokalizacji instalacji Macro Deck.\n\nPrzeciągnij Macro Deck do folderu Aplikacje w Finderze, a następnie otwórz go stamtąd."),
        ("Bootstrapper.Errors.MoveButtonMoveToApplications", "Przenieś do Aplikacji"),
        ("Bootstrapper.Errors.MoveCopyFailed", "Nie udało się skopiować Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveFailed", "{detail}\n\nPrzeciągnij Macro Deck do folderu Aplikacje w Finderze (lub do folderu Aplikacje we własnym folderze domowym), a następnie otwórz go stamtąd."),
        ("Bootstrapper.Errors.MoveInstallFailed", "Nie udało się zainstalować Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveNoDestinationFileName", "Miejsce docelowe instalacji Macro Deck nie ma nazwy pliku"),
        ("Bootstrapper.Errors.MovePrompt", "Macro Deck działa z obrazu dysku.\n\nPrzenieś go do folderu Aplikacje, aby go zainstalować. Macro Deck będzie się wtedy uruchamiał stamtąd.\n\nUruchamianie Macro Deck z obrazu dysku nie jest obsługiwane: aplikacja nie może wtedy zapisać swojej konfiguracji ani zainstalować aktualizacji."),
        ("Bootstrapper.Errors.MovePromptReplacesExisting", "Macro Deck działa z obrazu dysku.\n\nPrzenieś go do folderu Aplikacje, aby go zainstalować. Macro Deck będzie się wtedy uruchamiał stamtąd.\n\nUruchamianie Macro Deck z obrazu dysku nie jest obsługiwane: aplikacja nie może wtedy zapisać swojej konfiguracji ani zainstalować aktualizacji.\n\nSpowoduje to zastąpienie istniejącego Macro Deck w folderze Aplikacje."),
        ("Bootstrapper.Errors.MoveSetAsideFailed", "Nie udało się odłożyć istniejącego Macro Deck: {error}"),
        ("Bootstrapper.Errors.MoveToApplicationsTitle", "Przenieś Macro Deck do Aplikacji"),
        ("Bootstrapper.Errors.NoFreePort", "Nie udało się przydzielić wolnego portu loopback dla hosta Macro Deck."),
        ("Bootstrapper.Errors.PortInUse", "Macro Deck nie mógł się uruchomić, ponieważ port {port} jest już używany przez inną aplikację.\nZamknij aplikację korzystającą z tego portu (lub wciąż działający Macro Deck) i spróbuj ponownie, albo uruchom Macro Deck z ustawioną zmienną MACRO_DECK_PORT wskazującą wolny port, aby to zmienić."),
        ("Bootstrapper.Errors.PortInUseWithLog", "Macro Deck nie mógł się uruchomić, ponieważ port {port} jest już używany przez inną aplikację.\nZamknij aplikację korzystającą z tego portu (lub wciąż działający Macro Deck) i spróbuj ponownie, albo uruchom Macro Deck z ustawioną zmienną MACRO_DECK_PORT wskazującą wolny port, aby to zmienić.\n\nDane wyjściowe hosta:\n{log}"),
        ("Bootstrapper.Errors.RestartFailed", "Macro Deck nie mógł się ponownie uruchomić. Zamknij go i uruchom ponownie, aby zastosować zmianę."),
        ("Bootstrapper.Files.OpenDialogFilter", "Pliki"),
        ("Bootstrapper.Menu.About", "O Macro Deck"),
        ("Bootstrapper.Menu.ArchiveFilter", "Archiwa Macro Deck"),
        ("Bootstrapper.Menu.Discord", "Macro Deck na Discordzie"),
        ("Bootstrapper.Menu.Edit", "Edytuj"),
        ("Bootstrapper.Menu.File", "Plik"),
        ("Bootstrapper.Menu.Help", "Pomoc"),
        ("Bootstrapper.Menu.Import", "Importuj…"),
        ("Bootstrapper.Menu.Settings", "Ustawienia…"),
        ("Bootstrapper.Menu.View", "Widok"),
        ("Bootstrapper.Menu.Window", "Okno"),
        ("Bootstrapper.Tray.Quit", "Zakończ"),
        ("Bootstrapper.Tray.Show", "Pokaż"),
        ("Bootstrapper.Update.AllFeedsFailed", "nie udało się sprawdzić aktualizacji w żadnym źródle ({reasons})"),
        ("Bootstrapper.Update.AlreadyInProgress", "Aktualizacja jest już instalowana."),
        ("Bootstrapper.Update.AvailableTitle", "Dostępna aktualizacja"),
        ("Bootstrapper.Update.BackupFailed", "Macro Deck nie mógł utworzyć kopii zapasowej przed aktualizacją, więc aktualizacja nie została zainstalowana. {error}"),
        ("Bootstrapper.Update.BackupGenericFailure", "Kopia zapasowa przed aktualizacją nie powiodła się."),
        ("Bootstrapper.Update.BackupHostUnreachable", "Host Macro Deck jest niedostępny, więc nie udało się utworzyć kopii zapasowej."),
        ("Bootstrapper.Update.BackupUnconfirmed", "Macro Deck nie mógł potwierdzić utworzenia kopii zapasowej."),
        ("Bootstrapper.Update.CheckFailed", "Nie udało się sprawdzić dostępności aktualizacji: {error}"),
        ("Bootstrapper.Update.ConfirmDownload", "Macro Deck {version} jest dostępny.\n\nPobrać i zainstalować teraz?"),
        ("Bootstrapper.Update.DownloadAndInstall", "Pobierz i zainstaluj"),
        ("Bootstrapper.Update.DownloadFailed", "Nie udało się pobrać aktualizacji: {error}"),
        ("Bootstrapper.Update.Downloaded", "Pobrano Macro Deck {version}.\n\nUruchom Macro Deck ponownie, aby zainstalować aktualizację."),
        ("Bootstrapper.Update.ExternalAvailable", "Dostępny jest Macro Deck {version}.\n\nPobierz go ze strony Macro Deck i zaktualizuj zainstalowany pakiet AppImage, DEB lub RPM. Macro Deck będzie działał dalej."),
        ("Bootstrapper.Update.HostStopFailed", "Nie udało się zatrzymać hosta Macro Deck, więc aktualizacja nie została zainstalowana. Zamknij Macro Deck całkowicie i spróbuj ponownie."),
        ("Bootstrapper.Update.InstallFailed", "Nie udało się zainstalować aktualizacji: {error}"),
        ("Bootstrapper.Update.Later", "Później"),
        ("Bootstrapper.Update.LinuxNotSupported", "Macro Deck nie instaluje aktualizacji samodzielnie w systemie Linux. Pobierz nową wersję z {downloadPageUrl} i zaktualizuj instalację AppImage, DEB lub RPM."),
        ("Bootstrapper.Update.NoUpdateAvailable", "Brak dostępnych aktualizacji."),
        ("Bootstrapper.Update.NotAvailableInBuild", "Aktualizacje nie są dostępne w tej wersji."),
        ("Bootstrapper.Update.NotInstalled", "Macro Deck działa z obrazu dysku lub tymczasowej kopii, więc nie może się samodzielnie zaktualizować. Przenieś Macro Deck do folderu Aplikacje i uruchom go stamtąd."),
        ("Bootstrapper.Update.OpenDownloadPage", "Otwórz stronę pobierania"),
        ("Bootstrapper.Update.PartialCheckFailed.One", "Nie można sprawdzić kanału aktualizacji {names}."),
        ("Bootstrapper.Update.PartialCheckFailed.Other", "Nie można sprawdzić kanałów aktualizacji {names}."),
        ("Bootstrapper.Update.RestartNow", "Uruchom ponownie teraz"),
    ]),
];
