using System.Text;
using MacroDeck.LicenseTool.Model;

namespace MacroDeck.LicenseTool.Output;

internal static class ThirdPartyNoticesWriter
{
	private const string Rule = "================================================================================";

	private static readonly (Ecosystem Ecosystem, string Heading)[] Sections =
	[
		(Ecosystem.NuGet, "NuGet packages (Macro Deck host)"),
		(Ecosystem.Npm, "npm packages (configuration UI and web client)"),
		(Ecosystem.Cargo, "Rust crates (Macro Deck desktop application)"),
		(Ecosystem.Asset, "Bundled assets"),
	];

	public static string Write(IEnumerable<Component> components, IReadOnlySet<string> allPlatforms)
	{
		var list = components.ToList();
		var textIds = new Dictionary<string, int>(StringComparer.Ordinal);
		var textUsers = new List<(string Content, List<string> Users)>();
		var builder = new StringBuilder();

		builder.Append("""
			THIRD-PARTY SOFTWARE NOTICES AND INFORMATION
			Macro Deck

			Macro Deck includes the third-party components listed below. Each component is
			provided under its own license, reproduced in the license texts section.
			Source code of components under the Mozilla Public License 2.0, the GNU Lesser
			General Public License or another license that requires it is available from
			the URL listed for each component.

			This file is generated by tools/src/MacroDeck.LicenseTool from the dependency
			graphs of what Macro Deck ships. Do not edit it by hand.

			""").Append('\n');

		foreach (var (ecosystem, heading) in Sections)
		{
			var section = list.Where(component => component.Ecosystem == ecosystem)
				.OrderBy(component => component.Name, StringComparer.OrdinalIgnoreCase)
				.ThenBy(component => component.Name, StringComparer.Ordinal)
				.ToList();
			if (section.Count == 0)
			{
				continue;
			}

			builder.Append(Rule).Append('\n').Append(heading).Append('\n').Append(Rule).Append("\n\n");
			foreach (var component in section)
			{
				builder.Append(component.Name).Append('\n');
				builder.Append("  License: ").Append(string.Join("; ", component.SelectedLicenses)).Append('\n');
				var declared = component.DeclaredLicenses.Where(expression => !component.SelectedLicenses.Contains(expression)).ToList();
				if (declared.Count > 0)
				{
					builder.Append("  Declared: ").Append(string.Join("; ", declared)).Append('\n');
				}

				if (!string.IsNullOrEmpty(component.Url))
				{
					builder.Append("  URL: ").Append(component.Url).Append('\n');
				}

				if (component.Platforms.Count > 0 && !allPlatforms.IsSubsetOf(component.Platforms))
				{
					builder.Append("  Platforms: ").Append(string.Join(", ", component.Platforms)).Append('\n');
				}

				if (component.Note is not null)
				{
					builder.Append("  Note: ").Append(component.Note.Trim()).Append('\n');
				}

				var references = new List<int>();
				foreach (var text in component.Texts
					.OrderBy(text => text.Kind)
					.ThenBy(text => text.Title, StringComparer.Ordinal)
					.ThenBy(text => text.Content, StringComparer.Ordinal))
				{
					if (!textIds.TryGetValue(text.Content, out var id))
					{
						id = textUsers.Count + 1;
						textIds.Add(text.Content, id);
						textUsers.Add((text.Content, []));
					}

					if (!references.Contains(id))
					{
						references.Add(id);
						textUsers[id - 1].Users.Add(component.Name);
					}
				}

				builder.Append("  Texts: ").Append(string.Join(", ", references.Select(id => $"[{id}]"))).Append("\n\n");
			}
		}

		builder.Append(Rule).Append("\nLicense and notice texts\n").Append(Rule).Append("\n\n");
		for (var index = 0; index < textUsers.Count; index++)
		{
			var (content, users) = textUsers[index];
			builder.Append('[').Append(index + 1).Append("] ").Append(string.Join(", ", users.Distinct(StringComparer.Ordinal))).Append('\n');
			builder.Append("--------------------------------------------------------------------------------\n");
			builder.Append(content).Append("\n\n");
		}

		return builder.ToString().TrimEnd('\n') + "\n";
	}
}
