export const UiComponentProperties = {
  Events: 'events',
  MainSize: 'mainSize',
  Fill: 'fill',
  Direction: 'direction',
  Justify: 'justify',
  Align: 'align',
  Gap: 'gap',
  Padding: 'padding',
  Background: 'background',
  Text: 'text',
  Size: 'size',
  MinSize: 'minSize',
  Weight: 'weight',
  Role: 'role',
  Color: 'color',
  MaxLines: 'maxLines',
  Wrap: 'wrap',
  FontFace: 'fontFace',
  Source: 'source',
  Transition: 'transition',
  Fit: 'fit',
  Zoom: 'zoom',
  OffsetX: 'offsetX',
  OffsetY: 'offsetY',
  Opacity: 'opacity',
  Brightness: 'brightness',
  Saturation: 'saturation',
  Start: 'start',
  End: 'end',
  StartColor: 'startColor',
  EndColor: 'endColor',
  Marker: 'marker',
  Thickness: 'thickness',
  Value: 'value',
  Format: 'format',
  Seconds: 'seconds',
  Level: 'level',
  Step: 'step',
  LevelColor: 'levelColor',
  BorderStyle: 'borderStyle',
  BorderColor: 'borderColor',
  Corner: 'corner',
  Points: 'points',
  PlotTop: 'plotTop',
  Digits: 'digits',
  Placeholder: 'placeholder',
  Answer: 'answer',
} as const;

export const UI_COMPONENT_PROPERTIES_WELL_KNOWN: readonly string[] =
  Object.values(UiComponentProperties);
