name: Build Windows Installer

on:
  release:
    types: [published]

jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Update version
        run: |
          & .\MacroDeck.Setup\ChangeCsprojVersion.exe -p ".\MacroDeck\MacroDeck.csproj" -n "${{github.event.release.name}}"
      
      - name: Build
        run: |
          cd MacroDeck.Setup
          .\build_macrodeck_executable.cmd
          cd ..
        shell: cmd
      
      - name: Download Inno Setup
        run: Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.2.0.exe" -OutFile "innosetup.exe"

      - name: Install Inno Setup
        run: .\innosetup.exe /VERYSILENT /SUPPRESSMSGBOXES /SP- /NOCANCEL /NOICONS /CURRENTUSER
        shell: cmd
        
      - name: Build Installer
        run: |
            "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /F"macro-deck-${{github.event.release.name}}-setup-win" ".\MacroDeck.Setup\Macro Deck.iss"
        shell: cmd

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            .\MacroDeck.Setup\Result\macro-deck-${{github.event.release.name}}-setup-win.exe
       
