name: Inno Setup Installer

on:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    name: Build and test
  build-installer:
    needs: [tests]
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Build
        run: dotnet build

      - name: Install Inno Setup
        run: |
          Invoke-WebRequest "http://files.jrsoftware.org/is/6/innosetup-6.2.0.exe" -OutFile "innosetup.exe"
          Start-Process -FilePath .\innosetup.exe -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /SP- /NOCANCEL /NOICONS" -Wait

      - name: Build Installer
        run: |
          "& '$env:ISCC_PATH' 'MacroDeck.Setup\Macro Deck.iss"

      - name: Search for Installer
        id: search
        run: |
          $installer = Get-ChildItem -Path .\Output -Filter *.exe | Select-Object -Last 1
          Write-Output "##vso[task.setvariable variable=INSTALLER_NAME]$($installer.Name)"

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.INSTALLER_NAME }}
          path: Output/${{ env.INSTALLER_NAME }}

    env:
      ISCC_PATH: 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe'
