name: Build Windows Installer

on:
  release:
    types: [published]

jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Extract release name
        run: echo "RELEASE_NAME=${{ github.event.release.name }}" >> $GITHUB_ENV
      
      - name: Build
        run: |
            cd MacroDeck.Setup
            .\ChangeCsprojVersion.exe --p ..\MacroDeck\MacroDeck.csproj --v $RELEASE_NAME
            .\build_macrodeck_executable.cmd
            cd ..
        shell: cmd
      
      - name: Download Inno Setup
        run: Invoke-WebRequest -Uri "https://files.jrsoftware.org/is/6/innosetup-6.2.0.exe" -OutFile "innosetup.exe"

      - name: Install Inno Setup
        run: .\innosetup.exe /VERYSILENT /SUPPRESSMSGBOXES /SP- /NOCANCEL /NOICONS /CURRENTUSER
        shell: cmd
        
      - name: Build Installer
        run: |
            "C:\Program Files (x86)\Inno Setup 6\ISCC.exe /dMyOutputName=macro-deck-$RELEASE_NAME-win .\MacroDeck.Setup\Macro Deck.iss"
        shell: cmd

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          files: |
            .\MacroDeck.Setup\Result\macro-deck-$RELEASE_NAME-win.exe
       
