name: Build Windows Installer

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-windows-installer:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build
        run: |
            cd MacroDeck.Setup
            .\build_macrodeck_executable.cmd
            cd ..
        shell: cmd
      
      - name: Download Inno Setup
        run: Invoke-WebRequest -Uri "http://files.jrsoftware.org/is/6/innosetup-6.2.0.exe" -OutFile "innosetup.exe"

      - name: Install Inno Setup
        run: .\innosetup.exe /VERYSILENT /SUPPRESSMSGBOXES /SP- /NOCANCEL /NOICONS
        shell: cmd

      - name: Build Installer
        run: "'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' '.\MacroDeck.Setup\Macro Deck.iss'"
        shell: cmd

      - name: Search for Installer
        id: search
        run: |
          $installer = Get-ChildItem -Path .\Result -Filter *.exe | Select-Object -Last 1
          Write-Output "##vso[task.setvariable variable=INSTALLER_NAME]$($installer.Name)"

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.INSTALLER_NAME }}
          path: Output/${{ env.INSTALLER_NAME }}
