name: Build and Release Windows Installer

on:
  workflow_call:
    inputs:
      upload-url:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build-windows-installer:
    name: Build Windows Installer
    runs-on: windows-latest
    
    env:
      ISCC_PATH: 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe'
      INNO_SETUP_DIR: 'C:\Program Files (x86)\Inno Setup 6'
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Verify Inno Setup installation
        run: |
            Write-Output "Inno Setup path: '${{ env.ISCC_PATH }}'"
            if (Test-Path '${{ env.ISCC_PATH }}') {
              Write-Output "Inno Setup is installed."
            } else {
              Write-Output "Inno Setup installation is not installed."
              exit 1
            }

      - name: Build Macro Deck for Windows
        run: |
            dotnet restore ".\MacroDeck\MacroDeck.csproj"
            dotnet build ".\MacroDeck\MacroDeck.csproj" -c Release -o ".\MacroDeck\bin\Release" -r win-x64
            dotnet publish ".\MacroDeck\MacroDeck.csproj" -c Release -o ".\MacroDeck\bin\Publish" -r win-x64 --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true
            copy ".\MacroDeck\bin\Release\Macro Deck 2.dll" ".\MacroDeck\bin\Publish"
        shell: cmd
        
      - name: Build Macro Deck installer for Windows
        run: |
            "${{ env.ISCC_PATH }}" /F"macro-deck-${{ inputs.version }}-win" "MacroDeck.Setup\Macro Deck.iss"
        shell: cmd
      
      - name: Calculate File Size and Hash
        id: filehash
        run: |
          $filehash = Get-FileHash -Algorithm SHA256 -Path "MacroDeck.Setup\Result\macro-deck-${{ inputs.version }}-win.exe" | ForEach-Object Hash
          echo "FILE_HASH=$filehash" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
          $filesize = (Get-Item "MacroDeck.Setup\Result\macro-deck-${{ inputs.version }}-win.exe").Length
          echo "FILE_SIZE=$filesize" | Out-File -Append -FilePath $env:GITHUB_ENV -Encoding utf8
        shell: pwsh

      - name: Upload Windows installer to release
        uses: softprops/action-gh-release@v1
        with:
          files: 'MacroDeck.Setup\Result\macro-deck-${{ inputs.version }}-win.exe'
          tag_name: "v${{ inputs.version }}"
      
      - name: Push Update to the API
        uses: Macro-Deck-App/Actions/push-to-update-api@main
        with:
          version: ${{ inputs.version }}
          platform: "WinX64"
          file-name: "macro-deck-${{ inputs.version }}-win.exe"
          file-hash: ${{ env.FILE_HASH }}
          file-size: ${{ env.FILE_SIZE }}
          update-service-token: ${{ secrets.UPDATE_SERVICE_TOKEN }}
