name: Build and Release Windows Installer

on:
  workflow_call:
    inputs:
      upload-url:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build-windows-installer:
    name: Build Windows Installer
    runs-on: windows-latest
    
    env:
      ISCC_PATH: 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe'
      INNO_SETUP_DIR: 'C:\Program Files (x86)\Inno Setup 6'
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Verify Inno Setup installation
        run: |
            Write-Output "Inno Setup path: '${{ env.ISCC_PATH }}'"
            if (Test-Path '${{ env.ISCC_PATH }}') {
              Write-Output "Inno Setup is installed."
            } else {
              Write-Output "Inno Setup installation is not installed."
              exit 1
            }
            
      - name: Update project version
        run: |
          [xml]$csproj = Get-Content -Path "${{ github.workspace }}\MacroDeck\MacroDeck.csproj"
          $csproj.Project.PropertyGroup.Version = "${{ inputs.version }}"
          $csproj.OuterXml | Set-Content -Path "${{ github.workspace }}\MacroDeck\MacroDeck.csproj"
        shell: pwsh

      - name: Build Macro Deck for Windows
        run: |
            dotnet restore ".\MacroDeck\MacroDeck.csproj"
            dotnet build ".\MacroDeck\MacroDeck.csproj" -c Release -o ".\MacroDeck\bin\Release" -r win-x64
            dotnet publish ".\MacroDeck\MacroDeck.csproj" -c Release -o ".\MacroDeck\bin\Publish" -r win-x64 --self-contained true -p:IncludeNativeLibrariesForSelfExtract=true
            copy ".\MacroDeck\bin\Release\Macro Deck 2.dll" ".\MacroDeck\bin\Publish"
        shell: cmd
        
      - name: Build Macro Deck installer for Windows
        run: |
            "${{ env.ISCC_PATH }}" /F"macro-deck-${{ inputs.version }}-win" "MacroDeck.Setup\Macro Deck.iss"
        shell: cmd
      
      - name: Calculate file hash
        id: filehash
        run: |
          $filehash = Get-FileHash -Algorithm SHA256 -Path "MacroDeck.Setup\Result\macro-deck-${{ inputs.version }}-win.exe" | ForEach-Object Hash
          echo "::set-output name=filehash::$filehash"
        shell: pwsh
      
      - name: Calculate file size
        id: filesize
        run: |
          $filesize = (Get-Item "MacroDeck.Setup\Result\macro-deck-${{ inputs.version }}-win.exe").Length
          echo "::set-output name=filesize::$filesize"
        shell: pwsh

      - name: Upload Windows installer to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ inputs.upload-url }}
          asset_path: 'MacroDeck.Setup\Result\macro-deck-${{ inputs.version }}-win.exe'
          asset_name: macro-deck-${{ inputs.version }}-win.exe
          asset_content_type: application/octet-stream
      
      - name: Push Update to the API
        run: >
            curl -X 'POST' \
              'https://update.api.macro-deck.app/files/${{ inputs.version }}/${{ inputs.platform }}'
              -H 'accept: */*'
              -H 'x-admin-token: ${{ secrets.UPDATE_SERVICE_TOKEN }}'
              -H 'Content-Type: application/json'
              -d '{
              "fileName": ${{ inputs.filename }},
              "fileProvider": "GitHub",
              "fileHash": ${{ inputs.filehash }},
              "fileSize": ${{ inputs.filesize }}
              }'
