name: Build Windows Installer

on:
  release:
    types: [published]

jobs:
  check-release-name:
      runs-on: ubuntu-latest
      
      steps:
        - name: Check tag format
          run: |
            RELEASE_NAME="${{ github.event.release.name }}"

            BASE_PATTERN='^[0-9]+\.[0-9]+\.[0-9]+$'
            PREVIEW_PATTERN='^[0-9]+\.[0-9]+\.[0-9]+-preview[0-9]+$'

            if [[ ! ${RELEASE_NAME} =~ ${BASE_PATTERN} ]] && [[ ! ${RELEASE_NAME} =~ ${PREVIEW_PATTERN} ]]; then
              echo "Release name '${RELEASE_NAME}' doesn't match the expected format (X.X.X or X.X.X-previewX)"
              exit 1
            fi
          
  build-windows-installer:
    runs-on: windows-latest
    needs: check-release-name
    
    env:
      ISCC_PATH: 'C:\Program Files (x86)\Inno Setup 6\ISCC.exe'
      INNO_SETUP_DIR: 'C:\Program Files (x86)\Inno Setup 6'
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Verify Inno Setup installation
        run: |
            if (Test-Path ${{ env.INNO_SETUP_PATH }}) {
              Write-Output "Inno Setup is installed."
            } else {
              Write-Output "Inno Setup installation is not installed."
              exit 1
            }
            
      - name: Build Macro Deck for Windows
        run: |
          cd MacroDeck.Setup
          .\ChangeCsprojVersion.exe -p "${{ github.workspace }}\MacroDeck\MacroDeck.csproj" -n "${{github.event.release.name}}"
          .\build_macrodeck_executable.cmd
        shell: cmd
        
      - name: Build Macro Deck installer for Windows
        run: |
            & ${{ env.INNO_SETUP_PATH }} /F"macro-deck-${{github.event.release.name}}-win" "MacroDeck.Setup\Macro Deck.iss"

      - name: Upload Windows installer to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.INNO_SETUP_DIR }}\macro-deck-${{github.event.release.name}}-win.exe
          asset_name: macro-deck-${{github.event.release.name}}-win.exe
          asset_content_type: application/octet-stream
