name: Build Windows Installer

on:
  workflow_call:
    version:
      description: 'Version'     
      required: true
      type: string

jobs:
  check-release-name:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check tag format
        run: |
          RELEASE_NAME=${{ inputs.version }}

          BASE_PATTERN='^[0-9]+\.[0-9]+\.[0-9]+$'
          PREVIEW_PATTERN='^[0-9]+\.[0-9]+\.[0-9]+-preview[0-9]+$'

          if [[ ! ${RELEASE_NAME} =~ ${BASE_PATTERN} ]] && [[ ! ${RELEASE_NAME} =~ ${PREVIEW_PATTERN} ]]; then
            echo "Release name '${RELEASE_NAME}' doesn't match the expected format (X.X.X or X.X.X-previewX)"
            exit 1
          fi