name: CI

on:
  workflow_call:
  pull_request:
    branches:
      - 'production'
      - 'main'
  push:
    branches:
      - '!production'
      - '!main'
      
jobs:
  tests:
    name: Execute Tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit
