name: Continuous integration testing

on:
  workflow_call:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
      
jobs:
  tests:
    name: Execute Tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit