name: Create Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        type: choice
        options:
          - minor_beta
          - major_beta
          - patch
          - minor
          - major
        required: true

jobs:
  release:
    name: "Release Version"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          github-token: "${{secrets.GITHUB_TOKEN}}"
          
      - name: Fetch Version From API
        uses: Macro-Deck-App/Actions/fetch-version@main
        id: fetch_version
        with:
          releaseType: ${{ github.event.inputs.releaseType }}

      - name: "Create Tag And Release"
        uses: Macro-Deck-App/Actions/create-github-release@main
        with:
          github-token: "${{secrets.GITHUB_TOKEN}}"
          isBeta: ${{ steps.fetch_version.outputs.isBeta }}
          version: ${{steps.fetch_version.outputs.version}}
            
      - name: "Notify Discord"
        uses: Macro-Deck-App/Actions/discord-notify-release@main
        with:
          version: ${{ steps.fetch_version.outputs.version }}
          isBeta: ${{ steps.fetch_version.outputs.isBeta }}
          webhook_key: ${{ secrets.WEBHOOK_KEY }}
