name: Create Release

on:
  release:
    published:

jobs:
  tests:
    name: Execute Tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    
  release-windows:
    name: "Build and Push Macro Deck for Windows"
    uses: ./.github/workflows/build-push-windows.yml
    needs: [release-github, get-version]
    secrets: inherit
    with:
      version: ${{ needs.get-version.outputs.version }}
      upload-url: ${{ needs.release-github.outputs.upload-url }}
      
  create-pull-request:
    name: "Create pull-request back to develop"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [get-version, bump-version, release-windows, release-github]
    steps: 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          branch: main
          title: Bump Macro Deck version to ${{ needs.get-version.outputs.version }}
          body: Bumps the version of Macro Deck to ${{ needs.get-version.outputs.version }}
            
  notify:
    name: "Notify"
    runs-on: ubuntu-latest
    needs: [get-version, release-windows]
    steps:
      - uses: Macro-Deck-App/Actions/discord-notify-release@main
        with:
          version: ${{ needs.get-version.outputs.version }}
          is-beta: ${{ needs.get-version.outputs.is-beta }}
          webhook-token: ${{ secrets.WEBHOOK_KEY }}
