name: Create Release

on:
  release:
    types: [published]

jobs:
  tests:
    name: Execute Tests
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    
  release-windows:
    name: "Build and Push Macro Deck for Windows"
    uses: ./.github/workflows/build-push-windows.yml
    needs: [tests]
    secrets: inherit
    with:
      version: ${{ github.event.release.name }}
            
  notify:
    name: "Notify"
    runs-on: ubuntu-latest
    needs: [release-windows]
    steps:
      - uses: Macro-Deck-App/Actions/discord-notify-release@main
        with:
          version: ${{ github.event.release.name }}
          is-beta: ${{ github.event.release.prerelease }}
          webhook-token: ${{ secrets.WEBHOOK_KEY }}
