name: Release Created

on:
  release:
    types: [published]

jobs:
  validate_version:
    name: Validate Version
    runs-on: ubuntu-latest
    steps:
      - uses: Macro-Deck-App/Actions/validate-version@main
        with:
          version: ${{ github.event.release.name }}
      
  tests:
    name: Execute Tests
    needs: [validate_version]
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    
  release-windows:
    name: Build and Push Macro Deck for Windows
    uses: ./.github/workflows/build-push-windows.yml
    needs: [validate_version, tests]
    secrets: inherit
    with:
      version: ${{ github.event.release.name }}
      channel: ${{ github.event.release.prerelease && 'Preview' || 'Release' }}
