name: Run Tests

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Execute unit tests
      run: |
          dotnet restore "MacroDeck.Tests\MacroDeck.Tests.csproj"
          dotnet test "MacroDeck.Tests\MacroDeck.Tests.csproj"
      shell: bash
