name: Run Tests

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      
    - name: Execute unit tests
      run: |
          dotnet restore "tests\MacroDeck.Tests\MacroDeck.Tests.csproj"
          dotnet test "tests\MacroDeck.Tests\MacroDeck.Tests.csproj"
      shell: cmd
