name: Run Tests

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: "Setup .NET"
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          7.0.x
      
    - name: Execute unit tests
      run: |
          dotnet restore -property:EnableWindowsTargeting=true "MacroDeck.Tests\MacroDeck.Tests.csproj"
          dotnet test -property:EnableWindowsTargeting=true "MacroDeck.Tests\MacroDeck.Tests.csproj"
      shell: bash
